// Code generated by go-swagger; DO NOT EDIT.

package inventory_updates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// InventoryUpdatesInventoryUpdatesCancelCreateReader is a Reader for the InventoryUpdatesInventoryUpdatesCancelCreate structure.
type InventoryUpdatesInventoryUpdatesCancelCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InventoryUpdatesInventoryUpdatesCancelCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewInventoryUpdatesInventoryUpdatesCancelCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewInventoryUpdatesInventoryUpdatesCancelCreateCreated creates a InventoryUpdatesInventoryUpdatesCancelCreateCreated with default headers values
func NewInventoryUpdatesInventoryUpdatesCancelCreateCreated() *InventoryUpdatesInventoryUpdatesCancelCreateCreated {
	return &InventoryUpdatesInventoryUpdatesCancelCreateCreated{}
}

/*
InventoryUpdatesInventoryUpdatesCancelCreateCreated describes a response with status code 201, with default header values.

InventoryUpdatesInventoryUpdatesCancelCreateCreated inventory updates inventory updates cancel create created
*/
type InventoryUpdatesInventoryUpdatesCancelCreateCreated struct {
}

// IsSuccess returns true when this inventory updates inventory updates cancel create created response has a 2xx status code
func (o *InventoryUpdatesInventoryUpdatesCancelCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this inventory updates inventory updates cancel create created response has a 3xx status code
func (o *InventoryUpdatesInventoryUpdatesCancelCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this inventory updates inventory updates cancel create created response has a 4xx status code
func (o *InventoryUpdatesInventoryUpdatesCancelCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this inventory updates inventory updates cancel create created response has a 5xx status code
func (o *InventoryUpdatesInventoryUpdatesCancelCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this inventory updates inventory updates cancel create created response a status code equal to that given
func (o *InventoryUpdatesInventoryUpdatesCancelCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *InventoryUpdatesInventoryUpdatesCancelCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/inventory_updates/{id}/cancel/][%d] inventoryUpdatesInventoryUpdatesCancelCreateCreated ", 201)
}

func (o *InventoryUpdatesInventoryUpdatesCancelCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/inventory_updates/{id}/cancel/][%d] inventoryUpdatesInventoryUpdatesCancelCreateCreated ", 201)
}

func (o *InventoryUpdatesInventoryUpdatesCancelCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
