// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSchedulesSchedulesDeleteParams creates a new SchedulesSchedulesDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSchedulesSchedulesDeleteParams() *SchedulesSchedulesDeleteParams {
	return &SchedulesSchedulesDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSchedulesSchedulesDeleteParamsWithTimeout creates a new SchedulesSchedulesDeleteParams object
// with the ability to set a timeout on a request.
func NewSchedulesSchedulesDeleteParamsWithTimeout(timeout time.Duration) *SchedulesSchedulesDeleteParams {
	return &SchedulesSchedulesDeleteParams{
		timeout: timeout,
	}
}

// NewSchedulesSchedulesDeleteParamsWithContext creates a new SchedulesSchedulesDeleteParams object
// with the ability to set a context for a request.
func NewSchedulesSchedulesDeleteParamsWithContext(ctx context.Context) *SchedulesSchedulesDeleteParams {
	return &SchedulesSchedulesDeleteParams{
		Context: ctx,
	}
}

// NewSchedulesSchedulesDeleteParamsWithHTTPClient creates a new SchedulesSchedulesDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewSchedulesSchedulesDeleteParamsWithHTTPClient(client *http.Client) *SchedulesSchedulesDeleteParams {
	return &SchedulesSchedulesDeleteParams{
		HTTPClient: client,
	}
}

/*
SchedulesSchedulesDeleteParams contains all the parameters to send to the API endpoint

	for the schedules schedules delete operation.

	Typically these are written to a http.Request.
*/
type SchedulesSchedulesDeleteParams struct {

	// ID.
	ID string

	/* Search.

	   A search term.
	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the schedules schedules delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchedulesSchedulesDeleteParams) WithDefaults() *SchedulesSchedulesDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the schedules schedules delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchedulesSchedulesDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the schedules schedules delete params
func (o *SchedulesSchedulesDeleteParams) WithTimeout(timeout time.Duration) *SchedulesSchedulesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the schedules schedules delete params
func (o *SchedulesSchedulesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the schedules schedules delete params
func (o *SchedulesSchedulesDeleteParams) WithContext(ctx context.Context) *SchedulesSchedulesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the schedules schedules delete params
func (o *SchedulesSchedulesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the schedules schedules delete params
func (o *SchedulesSchedulesDeleteParams) WithHTTPClient(client *http.Client) *SchedulesSchedulesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the schedules schedules delete params
func (o *SchedulesSchedulesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the schedules schedules delete params
func (o *SchedulesSchedulesDeleteParams) WithID(id string) *SchedulesSchedulesDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the schedules schedules delete params
func (o *SchedulesSchedulesDeleteParams) SetID(id string) {
	o.ID = id
}

// WithSearch adds the search to the schedules schedules delete params
func (o *SchedulesSchedulesDeleteParams) WithSearch(search *string) *SchedulesSchedulesDeleteParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the schedules schedules delete params
func (o *SchedulesSchedulesDeleteParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *SchedulesSchedulesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
