// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProjectsProjectsSchedulesCreateReader is a Reader for the ProjectsProjectsSchedulesCreate structure.
type ProjectsProjectsSchedulesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectsProjectsSchedulesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewProjectsProjectsSchedulesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewProjectsProjectsSchedulesCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewProjectsProjectsSchedulesCreateCreated creates a ProjectsProjectsSchedulesCreateCreated with default headers values
func NewProjectsProjectsSchedulesCreateCreated() *ProjectsProjectsSchedulesCreateCreated {
	return &ProjectsProjectsSchedulesCreateCreated{}
}

/*
ProjectsProjectsSchedulesCreateCreated describes a response with status code 201, with default header values.

ProjectsProjectsSchedulesCreateCreated projects projects schedules create created
*/
type ProjectsProjectsSchedulesCreateCreated struct {
}

// IsSuccess returns true when this projects projects schedules create created response has a 2xx status code
func (o *ProjectsProjectsSchedulesCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this projects projects schedules create created response has a 3xx status code
func (o *ProjectsProjectsSchedulesCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this projects projects schedules create created response has a 4xx status code
func (o *ProjectsProjectsSchedulesCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this projects projects schedules create created response has a 5xx status code
func (o *ProjectsProjectsSchedulesCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this projects projects schedules create created response a status code equal to that given
func (o *ProjectsProjectsSchedulesCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *ProjectsProjectsSchedulesCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/projects/{id}/schedules/][%d] projectsProjectsSchedulesCreateCreated ", 201)
}

func (o *ProjectsProjectsSchedulesCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/projects/{id}/schedules/][%d] projectsProjectsSchedulesCreateCreated ", 201)
}

func (o *ProjectsProjectsSchedulesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProjectsProjectsSchedulesCreateBadRequest creates a ProjectsProjectsSchedulesCreateBadRequest with default headers values
func NewProjectsProjectsSchedulesCreateBadRequest() *ProjectsProjectsSchedulesCreateBadRequest {
	return &ProjectsProjectsSchedulesCreateBadRequest{}
}

/*
ProjectsProjectsSchedulesCreateBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type ProjectsProjectsSchedulesCreateBadRequest struct {
}

// IsSuccess returns true when this projects projects schedules create bad request response has a 2xx status code
func (o *ProjectsProjectsSchedulesCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this projects projects schedules create bad request response has a 3xx status code
func (o *ProjectsProjectsSchedulesCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this projects projects schedules create bad request response has a 4xx status code
func (o *ProjectsProjectsSchedulesCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this projects projects schedules create bad request response has a 5xx status code
func (o *ProjectsProjectsSchedulesCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this projects projects schedules create bad request response a status code equal to that given
func (o *ProjectsProjectsSchedulesCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ProjectsProjectsSchedulesCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/projects/{id}/schedules/][%d] projectsProjectsSchedulesCreateBadRequest ", 400)
}

func (o *ProjectsProjectsSchedulesCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v2/projects/{id}/schedules/][%d] projectsProjectsSchedulesCreateBadRequest ", 400)
}

func (o *ProjectsProjectsSchedulesCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
ProjectsProjectsSchedulesCreateBody projects projects schedules create body
swagger:model ProjectsProjectsSchedulesCreateBody
*/
type ProjectsProjectsSchedulesCreateBody struct {

	// description
	Description string `json:"description,omitempty"`

	// diff mode
	DiffMode bool `json:"diff_mode,omitempty"`

	// Enables processing of this schedule.
	Enabled bool `json:"enabled,omitempty"`

	// extra data
	ExtraData string `json:"extra_data,omitempty"`

	// Inventory applied as a prompt, assuming job template prompts for inventory
	Inventory int64 `json:"inventory,omitempty"`

	// job tags
	JobTags string `json:"job_tags,omitempty"`

	// job type
	JobType string `json:"job_type,omitempty"`

	// limit
	Limit string `json:"limit,omitempty"`

	// name
	// Required: true
	Name *string `json:"name"`

	// A value representing the schedules iCal recurrence rule.
	// Required: true
	Rrule *string `json:"rrule"`

	// scm branch
	ScmBranch string `json:"scm_branch,omitempty"`

	// skip tags
	SkipTags string `json:"skip_tags,omitempty"`

	// unified job template
	// Required: true
	UnifiedJobTemplate *int64 `json:"unified_job_template"`

	// verbosity
	Verbosity string `json:"verbosity,omitempty"`
}

// Validate validates this projects projects schedules create body
func (o *ProjectsProjectsSchedulesCreateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateRrule(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUnifiedJobTemplate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ProjectsProjectsSchedulesCreateBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

func (o *ProjectsProjectsSchedulesCreateBody) validateRrule(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"rrule", "body", o.Rrule); err != nil {
		return err
	}

	return nil
}

func (o *ProjectsProjectsSchedulesCreateBody) validateUnifiedJobTemplate(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"unified_job_template", "body", o.UnifiedJobTemplate); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this projects projects schedules create body based on context it is used
func (o *ProjectsProjectsSchedulesCreateBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ProjectsProjectsSchedulesCreateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ProjectsProjectsSchedulesCreateBody) UnmarshalBinary(b []byte) error {
	var res ProjectsProjectsSchedulesCreateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
