// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ProjectsProjectsTeamsListReader is a Reader for the ProjectsProjectsTeamsList structure.
type ProjectsProjectsTeamsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectsProjectsTeamsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProjectsProjectsTeamsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewProjectsProjectsTeamsListOK creates a ProjectsProjectsTeamsListOK with default headers values
func NewProjectsProjectsTeamsListOK() *ProjectsProjectsTeamsListOK {
	return &ProjectsProjectsTeamsListOK{}
}

/*
ProjectsProjectsTeamsListOK describes a response with status code 200, with default header values.

ProjectsProjectsTeamsListOK projects projects teams list o k
*/
type ProjectsProjectsTeamsListOK struct {
}

// IsSuccess returns true when this projects projects teams list o k response has a 2xx status code
func (o *ProjectsProjectsTeamsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this projects projects teams list o k response has a 3xx status code
func (o *ProjectsProjectsTeamsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this projects projects teams list o k response has a 4xx status code
func (o *ProjectsProjectsTeamsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this projects projects teams list o k response has a 5xx status code
func (o *ProjectsProjectsTeamsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this projects projects teams list o k response a status code equal to that given
func (o *ProjectsProjectsTeamsListOK) IsCode(code int) bool {
	return code == 200
}

func (o *ProjectsProjectsTeamsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{id}/teams/][%d] projectsProjectsTeamsListOK ", 200)
}

func (o *ProjectsProjectsTeamsListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/projects/{id}/teams/][%d] projectsProjectsTeamsListOK ", 200)
}

func (o *ProjectsProjectsTeamsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
