// Code generated by go-swagger; DO NOT EDIT.

package workflow_jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WorkflowJobsWorkflowJobsCancelCreateReader is a Reader for the WorkflowJobsWorkflowJobsCancelCreate structure.
type WorkflowJobsWorkflowJobsCancelCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkflowJobsWorkflowJobsCancelCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewWorkflowJobsWorkflowJobsCancelCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWorkflowJobsWorkflowJobsCancelCreateCreated creates a WorkflowJobsWorkflowJobsCancelCreateCreated with default headers values
func NewWorkflowJobsWorkflowJobsCancelCreateCreated() *WorkflowJobsWorkflowJobsCancelCreateCreated {
	return &WorkflowJobsWorkflowJobsCancelCreateCreated{}
}

/*
WorkflowJobsWorkflowJobsCancelCreateCreated describes a response with status code 201, with default header values.

WorkflowJobsWorkflowJobsCancelCreateCreated workflow jobs workflow jobs cancel create created
*/
type WorkflowJobsWorkflowJobsCancelCreateCreated struct {
}

// IsSuccess returns true when this workflow jobs workflow jobs cancel create created response has a 2xx status code
func (o *WorkflowJobsWorkflowJobsCancelCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this workflow jobs workflow jobs cancel create created response has a 3xx status code
func (o *WorkflowJobsWorkflowJobsCancelCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this workflow jobs workflow jobs cancel create created response has a 4xx status code
func (o *WorkflowJobsWorkflowJobsCancelCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this workflow jobs workflow jobs cancel create created response has a 5xx status code
func (o *WorkflowJobsWorkflowJobsCancelCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this workflow jobs workflow jobs cancel create created response a status code equal to that given
func (o *WorkflowJobsWorkflowJobsCancelCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *WorkflowJobsWorkflowJobsCancelCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/workflow_jobs/{id}/cancel/][%d] workflowJobsWorkflowJobsCancelCreateCreated ", 201)
}

func (o *WorkflowJobsWorkflowJobsCancelCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/workflow_jobs/{id}/cancel/][%d] workflowJobsWorkflowJobsCancelCreateCreated ", 201)
}

func (o *WorkflowJobsWorkflowJobsCancelCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
