// Code generated by go-swagger; DO NOT EDIT.

package workflow_jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewWorkflowJobsWorkflowJobsRelaunchCreateParams creates a new WorkflowJobsWorkflowJobsRelaunchCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewWorkflowJobsWorkflowJobsRelaunchCreateParams() *WorkflowJobsWorkflowJobsRelaunchCreateParams {
	return &WorkflowJobsWorkflowJobsRelaunchCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewWorkflowJobsWorkflowJobsRelaunchCreateParamsWithTimeout creates a new WorkflowJobsWorkflowJobsRelaunchCreateParams object
// with the ability to set a timeout on a request.
func NewWorkflowJobsWorkflowJobsRelaunchCreateParamsWithTimeout(timeout time.Duration) *WorkflowJobsWorkflowJobsRelaunchCreateParams {
	return &WorkflowJobsWorkflowJobsRelaunchCreateParams{
		timeout: timeout,
	}
}

// NewWorkflowJobsWorkflowJobsRelaunchCreateParamsWithContext creates a new WorkflowJobsWorkflowJobsRelaunchCreateParams object
// with the ability to set a context for a request.
func NewWorkflowJobsWorkflowJobsRelaunchCreateParamsWithContext(ctx context.Context) *WorkflowJobsWorkflowJobsRelaunchCreateParams {
	return &WorkflowJobsWorkflowJobsRelaunchCreateParams{
		Context: ctx,
	}
}

// NewWorkflowJobsWorkflowJobsRelaunchCreateParamsWithHTTPClient creates a new WorkflowJobsWorkflowJobsRelaunchCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewWorkflowJobsWorkflowJobsRelaunchCreateParamsWithHTTPClient(client *http.Client) *WorkflowJobsWorkflowJobsRelaunchCreateParams {
	return &WorkflowJobsWorkflowJobsRelaunchCreateParams{
		HTTPClient: client,
	}
}

/*
WorkflowJobsWorkflowJobsRelaunchCreateParams contains all the parameters to send to the API endpoint

	for the workflow jobs workflow jobs relaunch create operation.

	Typically these are written to a http.Request.
*/
type WorkflowJobsWorkflowJobsRelaunchCreateParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the workflow jobs workflow jobs relaunch create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WorkflowJobsWorkflowJobsRelaunchCreateParams) WithDefaults() *WorkflowJobsWorkflowJobsRelaunchCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the workflow jobs workflow jobs relaunch create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WorkflowJobsWorkflowJobsRelaunchCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the workflow jobs workflow jobs relaunch create params
func (o *WorkflowJobsWorkflowJobsRelaunchCreateParams) WithTimeout(timeout time.Duration) *WorkflowJobsWorkflowJobsRelaunchCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the workflow jobs workflow jobs relaunch create params
func (o *WorkflowJobsWorkflowJobsRelaunchCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the workflow jobs workflow jobs relaunch create params
func (o *WorkflowJobsWorkflowJobsRelaunchCreateParams) WithContext(ctx context.Context) *WorkflowJobsWorkflowJobsRelaunchCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the workflow jobs workflow jobs relaunch create params
func (o *WorkflowJobsWorkflowJobsRelaunchCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the workflow jobs workflow jobs relaunch create params
func (o *WorkflowJobsWorkflowJobsRelaunchCreateParams) WithHTTPClient(client *http.Client) *WorkflowJobsWorkflowJobsRelaunchCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the workflow jobs workflow jobs relaunch create params
func (o *WorkflowJobsWorkflowJobsRelaunchCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the workflow jobs workflow jobs relaunch create params
func (o *WorkflowJobsWorkflowJobsRelaunchCreateParams) WithID(id string) *WorkflowJobsWorkflowJobsRelaunchCreateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the workflow jobs workflow jobs relaunch create params
func (o *WorkflowJobsWorkflowJobsRelaunchCreateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *WorkflowJobsWorkflowJobsRelaunchCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
