// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// HostsHostsReadReader is a Reader for the HostsHostsRead structure.
type HostsHostsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HostsHostsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHostsHostsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewHostsHostsReadOK creates a HostsHostsReadOK with default headers values
func NewHostsHostsReadOK() *HostsHostsReadOK {
	return &HostsHostsReadOK{}
}

/*
HostsHostsReadOK describes a response with status code 200, with default header values.

HostsHostsReadOK hosts hosts read o k
*/
type HostsHostsReadOK struct {
}

// IsSuccess returns true when this hosts hosts read o k response has a 2xx status code
func (o *HostsHostsReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this hosts hosts read o k response has a 3xx status code
func (o *HostsHostsReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this hosts hosts read o k response has a 4xx status code
func (o *HostsHostsReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this hosts hosts read o k response has a 5xx status code
func (o *HostsHostsReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this hosts hosts read o k response a status code equal to that given
func (o *HostsHostsReadOK) IsCode(code int) bool {
	return code == 200
}

func (o *HostsHostsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/hosts/{id}/][%d] hostsHostsReadOK ", 200)
}

func (o *HostsHostsReadOK) String() string {
	return fmt.Sprintf("[GET /api/v2/hosts/{id}/][%d] hostsHostsReadOK ", 200)
}

func (o *HostsHostsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
