// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// HostsHostsListReader is a Reader for the HostsHostsList structure.
type HostsHostsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HostsHostsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHostsHostsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewHostsHostsListOK creates a HostsHostsListOK with default headers values
func NewHostsHostsListOK() *HostsHostsListOK {
	return &HostsHostsListOK{}
}

/*
HostsHostsListOK describes a response with status code 200, with default header values.

HostsHostsListOK hosts hosts list o k
*/
type HostsHostsListOK struct {
}

// IsSuccess returns true when this hosts hosts list o k response has a 2xx status code
func (o *HostsHostsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this hosts hosts list o k response has a 3xx status code
func (o *HostsHostsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this hosts hosts list o k response has a 4xx status code
func (o *HostsHostsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this hosts hosts list o k response has a 5xx status code
func (o *HostsHostsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this hosts hosts list o k response a status code equal to that given
func (o *HostsHostsListOK) IsCode(code int) bool {
	return code == 200
}

func (o *HostsHostsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/hosts/][%d] hostsHostsListOK ", 200)
}

func (o *HostsHostsListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/hosts/][%d] hostsHostsListOK ", 200)
}

func (o *HostsHostsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
