// Code generated by go-swagger; DO NOT EDIT.

package activity_streams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ActivityStreamsActivityStreamReadReader is a Reader for the ActivityStreamsActivityStreamRead structure.
type ActivityStreamsActivityStreamReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActivityStreamsActivityStreamReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActivityStreamsActivityStreamReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewActivityStreamsActivityStreamReadOK creates a ActivityStreamsActivityStreamReadOK with default headers values
func NewActivityStreamsActivityStreamReadOK() *ActivityStreamsActivityStreamReadOK {
	return &ActivityStreamsActivityStreamReadOK{}
}

/*
ActivityStreamsActivityStreamReadOK describes a response with status code 200, with default header values.

ActivityStreamsActivityStreamReadOK activity streams activity stream read o k
*/
type ActivityStreamsActivityStreamReadOK struct {
}

// IsSuccess returns true when this activity streams activity stream read o k response has a 2xx status code
func (o *ActivityStreamsActivityStreamReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this activity streams activity stream read o k response has a 3xx status code
func (o *ActivityStreamsActivityStreamReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this activity streams activity stream read o k response has a 4xx status code
func (o *ActivityStreamsActivityStreamReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this activity streams activity stream read o k response has a 5xx status code
func (o *ActivityStreamsActivityStreamReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this activity streams activity stream read o k response a status code equal to that given
func (o *ActivityStreamsActivityStreamReadOK) IsCode(code int) bool {
	return code == 200
}

func (o *ActivityStreamsActivityStreamReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/activity_stream/{id}/][%d] activityStreamsActivityStreamReadOK ", 200)
}

func (o *ActivityStreamsActivityStreamReadOK) String() string {
	return fmt.Sprintf("[GET /api/v2/activity_stream/{id}/][%d] activityStreamsActivityStreamReadOK ", 200)
}

func (o *ActivityStreamsActivityStreamReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
