// Code generated by go-swagger; DO NOT EDIT.

package credential_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CredentialTypesCredentialTypesTestCreateReader is a Reader for the CredentialTypesCredentialTypesTestCreate structure.
type CredentialTypesCredentialTypesTestCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CredentialTypesCredentialTypesTestCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCredentialTypesCredentialTypesTestCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewCredentialTypesCredentialTypesTestCreateAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewCredentialTypesCredentialTypesTestCreateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCredentialTypesCredentialTypesTestCreateCreated creates a CredentialTypesCredentialTypesTestCreateCreated with default headers values
func NewCredentialTypesCredentialTypesTestCreateCreated() *CredentialTypesCredentialTypesTestCreateCreated {
	return &CredentialTypesCredentialTypesTestCreateCreated{}
}

/*
CredentialTypesCredentialTypesTestCreateCreated describes a response with status code 201, with default header values.

CredentialTypesCredentialTypesTestCreateCreated credential types credential types test create created
*/
type CredentialTypesCredentialTypesTestCreateCreated struct {
}

// IsSuccess returns true when this credential types credential types test create created response has a 2xx status code
func (o *CredentialTypesCredentialTypesTestCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this credential types credential types test create created response has a 3xx status code
func (o *CredentialTypesCredentialTypesTestCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this credential types credential types test create created response has a 4xx status code
func (o *CredentialTypesCredentialTypesTestCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this credential types credential types test create created response has a 5xx status code
func (o *CredentialTypesCredentialTypesTestCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this credential types credential types test create created response a status code equal to that given
func (o *CredentialTypesCredentialTypesTestCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CredentialTypesCredentialTypesTestCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/credential_types/{id}/test/][%d] credentialTypesCredentialTypesTestCreateCreated ", 201)
}

func (o *CredentialTypesCredentialTypesTestCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/credential_types/{id}/test/][%d] credentialTypesCredentialTypesTestCreateCreated ", 201)
}

func (o *CredentialTypesCredentialTypesTestCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCredentialTypesCredentialTypesTestCreateAccepted creates a CredentialTypesCredentialTypesTestCreateAccepted with default headers values
func NewCredentialTypesCredentialTypesTestCreateAccepted() *CredentialTypesCredentialTypesTestCreateAccepted {
	return &CredentialTypesCredentialTypesTestCreateAccepted{}
}

/*
CredentialTypesCredentialTypesTestCreateAccepted describes a response with status code 202, with default header values.

Accepted
*/
type CredentialTypesCredentialTypesTestCreateAccepted struct {
}

// IsSuccess returns true when this credential types credential types test create accepted response has a 2xx status code
func (o *CredentialTypesCredentialTypesTestCreateAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this credential types credential types test create accepted response has a 3xx status code
func (o *CredentialTypesCredentialTypesTestCreateAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this credential types credential types test create accepted response has a 4xx status code
func (o *CredentialTypesCredentialTypesTestCreateAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this credential types credential types test create accepted response has a 5xx status code
func (o *CredentialTypesCredentialTypesTestCreateAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this credential types credential types test create accepted response a status code equal to that given
func (o *CredentialTypesCredentialTypesTestCreateAccepted) IsCode(code int) bool {
	return code == 202
}

func (o *CredentialTypesCredentialTypesTestCreateAccepted) Error() string {
	return fmt.Sprintf("[POST /api/v2/credential_types/{id}/test/][%d] credentialTypesCredentialTypesTestCreateAccepted ", 202)
}

func (o *CredentialTypesCredentialTypesTestCreateAccepted) String() string {
	return fmt.Sprintf("[POST /api/v2/credential_types/{id}/test/][%d] credentialTypesCredentialTypesTestCreateAccepted ", 202)
}

func (o *CredentialTypesCredentialTypesTestCreateAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCredentialTypesCredentialTypesTestCreateForbidden creates a CredentialTypesCredentialTypesTestCreateForbidden with default headers values
func NewCredentialTypesCredentialTypesTestCreateForbidden() *CredentialTypesCredentialTypesTestCreateForbidden {
	return &CredentialTypesCredentialTypesTestCreateForbidden{}
}

/*
CredentialTypesCredentialTypesTestCreateForbidden describes a response with status code 403, with default header values.

forbidden
*/
type CredentialTypesCredentialTypesTestCreateForbidden struct {
}

// IsSuccess returns true when this credential types credential types test create forbidden response has a 2xx status code
func (o *CredentialTypesCredentialTypesTestCreateForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this credential types credential types test create forbidden response has a 3xx status code
func (o *CredentialTypesCredentialTypesTestCreateForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this credential types credential types test create forbidden response has a 4xx status code
func (o *CredentialTypesCredentialTypesTestCreateForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this credential types credential types test create forbidden response has a 5xx status code
func (o *CredentialTypesCredentialTypesTestCreateForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this credential types credential types test create forbidden response a status code equal to that given
func (o *CredentialTypesCredentialTypesTestCreateForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CredentialTypesCredentialTypesTestCreateForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/credential_types/{id}/test/][%d] credentialTypesCredentialTypesTestCreateForbidden ", 403)
}

func (o *CredentialTypesCredentialTypesTestCreateForbidden) String() string {
	return fmt.Sprintf("[POST /api/v2/credential_types/{id}/test/][%d] credentialTypesCredentialTypesTestCreateForbidden ", 403)
}

func (o *CredentialTypesCredentialTypesTestCreateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
