// Code generated by go-swagger; DO NOT EDIT.

package credential_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCredentialTypesCredentialTypesCreateParams creates a new CredentialTypesCredentialTypesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCredentialTypesCredentialTypesCreateParams() *CredentialTypesCredentialTypesCreateParams {
	return &CredentialTypesCredentialTypesCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCredentialTypesCredentialTypesCreateParamsWithTimeout creates a new CredentialTypesCredentialTypesCreateParams object
// with the ability to set a timeout on a request.
func NewCredentialTypesCredentialTypesCreateParamsWithTimeout(timeout time.Duration) *CredentialTypesCredentialTypesCreateParams {
	return &CredentialTypesCredentialTypesCreateParams{
		timeout: timeout,
	}
}

// NewCredentialTypesCredentialTypesCreateParamsWithContext creates a new CredentialTypesCredentialTypesCreateParams object
// with the ability to set a context for a request.
func NewCredentialTypesCredentialTypesCreateParamsWithContext(ctx context.Context) *CredentialTypesCredentialTypesCreateParams {
	return &CredentialTypesCredentialTypesCreateParams{
		Context: ctx,
	}
}

// NewCredentialTypesCredentialTypesCreateParamsWithHTTPClient creates a new CredentialTypesCredentialTypesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewCredentialTypesCredentialTypesCreateParamsWithHTTPClient(client *http.Client) *CredentialTypesCredentialTypesCreateParams {
	return &CredentialTypesCredentialTypesCreateParams{
		HTTPClient: client,
	}
}

/*
CredentialTypesCredentialTypesCreateParams contains all the parameters to send to the API endpoint

	for the credential types credential types create operation.

	Typically these are written to a http.Request.
*/
type CredentialTypesCredentialTypesCreateParams struct {

	// Data.
	Data interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the credential types credential types create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CredentialTypesCredentialTypesCreateParams) WithDefaults() *CredentialTypesCredentialTypesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the credential types credential types create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CredentialTypesCredentialTypesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the credential types credential types create params
func (o *CredentialTypesCredentialTypesCreateParams) WithTimeout(timeout time.Duration) *CredentialTypesCredentialTypesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the credential types credential types create params
func (o *CredentialTypesCredentialTypesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the credential types credential types create params
func (o *CredentialTypesCredentialTypesCreateParams) WithContext(ctx context.Context) *CredentialTypesCredentialTypesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the credential types credential types create params
func (o *CredentialTypesCredentialTypesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the credential types credential types create params
func (o *CredentialTypesCredentialTypesCreateParams) WithHTTPClient(client *http.Client) *CredentialTypesCredentialTypesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the credential types credential types create params
func (o *CredentialTypesCredentialTypesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the credential types credential types create params
func (o *CredentialTypesCredentialTypesCreateParams) WithData(data interface{}) *CredentialTypesCredentialTypesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the credential types credential types create params
func (o *CredentialTypesCredentialTypesCreateParams) SetData(data interface{}) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *CredentialTypesCredentialTypesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
