// Code generated by go-swagger; DO NOT EDIT.

package credential_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CredentialTypesCredentialTypesPartialUpdateReader is a Reader for the CredentialTypesCredentialTypesPartialUpdate structure.
type CredentialTypesCredentialTypesPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CredentialTypesCredentialTypesPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCredentialTypesCredentialTypesPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCredentialTypesCredentialTypesPartialUpdateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCredentialTypesCredentialTypesPartialUpdateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCredentialTypesCredentialTypesPartialUpdateOK creates a CredentialTypesCredentialTypesPartialUpdateOK with default headers values
func NewCredentialTypesCredentialTypesPartialUpdateOK() *CredentialTypesCredentialTypesPartialUpdateOK {
	return &CredentialTypesCredentialTypesPartialUpdateOK{}
}

/*
CredentialTypesCredentialTypesPartialUpdateOK describes a response with status code 200, with default header values.

CredentialTypesCredentialTypesPartialUpdateOK credential types credential types partial update o k
*/
type CredentialTypesCredentialTypesPartialUpdateOK struct {
}

// IsSuccess returns true when this credential types credential types partial update o k response has a 2xx status code
func (o *CredentialTypesCredentialTypesPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this credential types credential types partial update o k response has a 3xx status code
func (o *CredentialTypesCredentialTypesPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this credential types credential types partial update o k response has a 4xx status code
func (o *CredentialTypesCredentialTypesPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this credential types credential types partial update o k response has a 5xx status code
func (o *CredentialTypesCredentialTypesPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this credential types credential types partial update o k response a status code equal to that given
func (o *CredentialTypesCredentialTypesPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *CredentialTypesCredentialTypesPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /api/v2/credential_types/{id}/][%d] credentialTypesCredentialTypesPartialUpdateOK ", 200)
}

func (o *CredentialTypesCredentialTypesPartialUpdateOK) String() string {
	return fmt.Sprintf("[PATCH /api/v2/credential_types/{id}/][%d] credentialTypesCredentialTypesPartialUpdateOK ", 200)
}

func (o *CredentialTypesCredentialTypesPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCredentialTypesCredentialTypesPartialUpdateUnauthorized creates a CredentialTypesCredentialTypesPartialUpdateUnauthorized with default headers values
func NewCredentialTypesCredentialTypesPartialUpdateUnauthorized() *CredentialTypesCredentialTypesPartialUpdateUnauthorized {
	return &CredentialTypesCredentialTypesPartialUpdateUnauthorized{}
}

/*
CredentialTypesCredentialTypesPartialUpdateUnauthorized describes a response with status code 401, with default header values.

CredentialTypesCredentialTypesPartialUpdateUnauthorized credential types credential types partial update unauthorized
*/
type CredentialTypesCredentialTypesPartialUpdateUnauthorized struct {
}

// IsSuccess returns true when this credential types credential types partial update unauthorized response has a 2xx status code
func (o *CredentialTypesCredentialTypesPartialUpdateUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this credential types credential types partial update unauthorized response has a 3xx status code
func (o *CredentialTypesCredentialTypesPartialUpdateUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this credential types credential types partial update unauthorized response has a 4xx status code
func (o *CredentialTypesCredentialTypesPartialUpdateUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this credential types credential types partial update unauthorized response has a 5xx status code
func (o *CredentialTypesCredentialTypesPartialUpdateUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this credential types credential types partial update unauthorized response a status code equal to that given
func (o *CredentialTypesCredentialTypesPartialUpdateUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CredentialTypesCredentialTypesPartialUpdateUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /api/v2/credential_types/{id}/][%d] credentialTypesCredentialTypesPartialUpdateUnauthorized ", 401)
}

func (o *CredentialTypesCredentialTypesPartialUpdateUnauthorized) String() string {
	return fmt.Sprintf("[PATCH /api/v2/credential_types/{id}/][%d] credentialTypesCredentialTypesPartialUpdateUnauthorized ", 401)
}

func (o *CredentialTypesCredentialTypesPartialUpdateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCredentialTypesCredentialTypesPartialUpdateForbidden creates a CredentialTypesCredentialTypesPartialUpdateForbidden with default headers values
func NewCredentialTypesCredentialTypesPartialUpdateForbidden() *CredentialTypesCredentialTypesPartialUpdateForbidden {
	return &CredentialTypesCredentialTypesPartialUpdateForbidden{}
}

/*
CredentialTypesCredentialTypesPartialUpdateForbidden describes a response with status code 403, with default header values.

forbidden
*/
type CredentialTypesCredentialTypesPartialUpdateForbidden struct {
}

// IsSuccess returns true when this credential types credential types partial update forbidden response has a 2xx status code
func (o *CredentialTypesCredentialTypesPartialUpdateForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this credential types credential types partial update forbidden response has a 3xx status code
func (o *CredentialTypesCredentialTypesPartialUpdateForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this credential types credential types partial update forbidden response has a 4xx status code
func (o *CredentialTypesCredentialTypesPartialUpdateForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this credential types credential types partial update forbidden response has a 5xx status code
func (o *CredentialTypesCredentialTypesPartialUpdateForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this credential types credential types partial update forbidden response a status code equal to that given
func (o *CredentialTypesCredentialTypesPartialUpdateForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CredentialTypesCredentialTypesPartialUpdateForbidden) Error() string {
	return fmt.Sprintf("[PATCH /api/v2/credential_types/{id}/][%d] credentialTypesCredentialTypesPartialUpdateForbidden ", 403)
}

func (o *CredentialTypesCredentialTypesPartialUpdateForbidden) String() string {
	return fmt.Sprintf("[PATCH /api/v2/credential_types/{id}/][%d] credentialTypesCredentialTypesPartialUpdateForbidden ", 403)
}

func (o *CredentialTypesCredentialTypesPartialUpdateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
