// Code generated by go-swagger; DO NOT EDIT.

package inventory_updates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewInventoryUpdatesInventoryUpdatesStdoutReadParams creates a new InventoryUpdatesInventoryUpdatesStdoutReadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInventoryUpdatesInventoryUpdatesStdoutReadParams() *InventoryUpdatesInventoryUpdatesStdoutReadParams {
	return &InventoryUpdatesInventoryUpdatesStdoutReadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewInventoryUpdatesInventoryUpdatesStdoutReadParamsWithTimeout creates a new InventoryUpdatesInventoryUpdatesStdoutReadParams object
// with the ability to set a timeout on a request.
func NewInventoryUpdatesInventoryUpdatesStdoutReadParamsWithTimeout(timeout time.Duration) *InventoryUpdatesInventoryUpdatesStdoutReadParams {
	return &InventoryUpdatesInventoryUpdatesStdoutReadParams{
		timeout: timeout,
	}
}

// NewInventoryUpdatesInventoryUpdatesStdoutReadParamsWithContext creates a new InventoryUpdatesInventoryUpdatesStdoutReadParams object
// with the ability to set a context for a request.
func NewInventoryUpdatesInventoryUpdatesStdoutReadParamsWithContext(ctx context.Context) *InventoryUpdatesInventoryUpdatesStdoutReadParams {
	return &InventoryUpdatesInventoryUpdatesStdoutReadParams{
		Context: ctx,
	}
}

// NewInventoryUpdatesInventoryUpdatesStdoutReadParamsWithHTTPClient creates a new InventoryUpdatesInventoryUpdatesStdoutReadParams object
// with the ability to set a custom HTTPClient for a request.
func NewInventoryUpdatesInventoryUpdatesStdoutReadParamsWithHTTPClient(client *http.Client) *InventoryUpdatesInventoryUpdatesStdoutReadParams {
	return &InventoryUpdatesInventoryUpdatesStdoutReadParams{
		HTTPClient: client,
	}
}

/*
InventoryUpdatesInventoryUpdatesStdoutReadParams contains all the parameters to send to the API endpoint

	for the inventory updates inventory updates stdout read operation.

	Typically these are written to a http.Request.
*/
type InventoryUpdatesInventoryUpdatesStdoutReadParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the inventory updates inventory updates stdout read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InventoryUpdatesInventoryUpdatesStdoutReadParams) WithDefaults() *InventoryUpdatesInventoryUpdatesStdoutReadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the inventory updates inventory updates stdout read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InventoryUpdatesInventoryUpdatesStdoutReadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the inventory updates inventory updates stdout read params
func (o *InventoryUpdatesInventoryUpdatesStdoutReadParams) WithTimeout(timeout time.Duration) *InventoryUpdatesInventoryUpdatesStdoutReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the inventory updates inventory updates stdout read params
func (o *InventoryUpdatesInventoryUpdatesStdoutReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the inventory updates inventory updates stdout read params
func (o *InventoryUpdatesInventoryUpdatesStdoutReadParams) WithContext(ctx context.Context) *InventoryUpdatesInventoryUpdatesStdoutReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the inventory updates inventory updates stdout read params
func (o *InventoryUpdatesInventoryUpdatesStdoutReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the inventory updates inventory updates stdout read params
func (o *InventoryUpdatesInventoryUpdatesStdoutReadParams) WithHTTPClient(client *http.Client) *InventoryUpdatesInventoryUpdatesStdoutReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the inventory updates inventory updates stdout read params
func (o *InventoryUpdatesInventoryUpdatesStdoutReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the inventory updates inventory updates stdout read params
func (o *InventoryUpdatesInventoryUpdatesStdoutReadParams) WithID(id string) *InventoryUpdatesInventoryUpdatesStdoutReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the inventory updates inventory updates stdout read params
func (o *InventoryUpdatesInventoryUpdatesStdoutReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *InventoryUpdatesInventoryUpdatesStdoutReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
