// Code generated by go-swagger; DO NOT EDIT.

package inventory_sources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// InventorySourcesInventorySourcesNotificationTemplatesSuccessListReader is a Reader for the InventorySourcesInventorySourcesNotificationTemplatesSuccessList structure.
type InventorySourcesInventorySourcesNotificationTemplatesSuccessListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InventorySourcesInventorySourcesNotificationTemplatesSuccessListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInventorySourcesInventorySourcesNotificationTemplatesSuccessListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewInventorySourcesInventorySourcesNotificationTemplatesSuccessListOK creates a InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK with default headers values
func NewInventorySourcesInventorySourcesNotificationTemplatesSuccessListOK() *InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK {
	return &InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK{}
}

/*
InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK describes a response with status code 200, with default header values.

InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK inventory sources inventory sources notification templates success list o k
*/
type InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK struct {
}

// IsSuccess returns true when this inventory sources inventory sources notification templates success list o k response has a 2xx status code
func (o *InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this inventory sources inventory sources notification templates success list o k response has a 3xx status code
func (o *InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this inventory sources inventory sources notification templates success list o k response has a 4xx status code
func (o *InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this inventory sources inventory sources notification templates success list o k response has a 5xx status code
func (o *InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this inventory sources inventory sources notification templates success list o k response a status code equal to that given
func (o *InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK) IsCode(code int) bool {
	return code == 200
}

func (o *InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/inventory_sources/{id}/notification_templates_success/][%d] inventorySourcesInventorySourcesNotificationTemplatesSuccessListOK ", 200)
}

func (o *InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/inventory_sources/{id}/notification_templates_success/][%d] inventorySourcesInventorySourcesNotificationTemplatesSuccessListOK ", 200)
}

func (o *InventorySourcesInventorySourcesNotificationTemplatesSuccessListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
