// Code generated by go-swagger; DO NOT EDIT.

package inventory_sources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// InventorySourcesInventorySourcesHostsDeleteReader is a Reader for the InventorySourcesInventorySourcesHostsDelete structure.
type InventorySourcesInventorySourcesHostsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InventorySourcesInventorySourcesHostsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewInventorySourcesInventorySourcesHostsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewInventorySourcesInventorySourcesHostsDeleteForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewInventorySourcesInventorySourcesHostsDeleteNoContent creates a InventorySourcesInventorySourcesHostsDeleteNoContent with default headers values
func NewInventorySourcesInventorySourcesHostsDeleteNoContent() *InventorySourcesInventorySourcesHostsDeleteNoContent {
	return &InventorySourcesInventorySourcesHostsDeleteNoContent{}
}

/*
InventorySourcesInventorySourcesHostsDeleteNoContent describes a response with status code 204, with default header values.

InventorySourcesInventorySourcesHostsDeleteNoContent inventory sources inventory sources hosts delete no content
*/
type InventorySourcesInventorySourcesHostsDeleteNoContent struct {
}

// IsSuccess returns true when this inventory sources inventory sources hosts delete no content response has a 2xx status code
func (o *InventorySourcesInventorySourcesHostsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this inventory sources inventory sources hosts delete no content response has a 3xx status code
func (o *InventorySourcesInventorySourcesHostsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this inventory sources inventory sources hosts delete no content response has a 4xx status code
func (o *InventorySourcesInventorySourcesHostsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this inventory sources inventory sources hosts delete no content response has a 5xx status code
func (o *InventorySourcesInventorySourcesHostsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this inventory sources inventory sources hosts delete no content response a status code equal to that given
func (o *InventorySourcesInventorySourcesHostsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *InventorySourcesInventorySourcesHostsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/inventory_sources/{id}/hosts/][%d] inventorySourcesInventorySourcesHostsDeleteNoContent ", 204)
}

func (o *InventorySourcesInventorySourcesHostsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/v2/inventory_sources/{id}/hosts/][%d] inventorySourcesInventorySourcesHostsDeleteNoContent ", 204)
}

func (o *InventorySourcesInventorySourcesHostsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInventorySourcesInventorySourcesHostsDeleteForbidden creates a InventorySourcesInventorySourcesHostsDeleteForbidden with default headers values
func NewInventorySourcesInventorySourcesHostsDeleteForbidden() *InventorySourcesInventorySourcesHostsDeleteForbidden {
	return &InventorySourcesInventorySourcesHostsDeleteForbidden{}
}

/*
InventorySourcesInventorySourcesHostsDeleteForbidden describes a response with status code 403, with default header values.

forbidden
*/
type InventorySourcesInventorySourcesHostsDeleteForbidden struct {
}

// IsSuccess returns true when this inventory sources inventory sources hosts delete forbidden response has a 2xx status code
func (o *InventorySourcesInventorySourcesHostsDeleteForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this inventory sources inventory sources hosts delete forbidden response has a 3xx status code
func (o *InventorySourcesInventorySourcesHostsDeleteForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this inventory sources inventory sources hosts delete forbidden response has a 4xx status code
func (o *InventorySourcesInventorySourcesHostsDeleteForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this inventory sources inventory sources hosts delete forbidden response has a 5xx status code
func (o *InventorySourcesInventorySourcesHostsDeleteForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this inventory sources inventory sources hosts delete forbidden response a status code equal to that given
func (o *InventorySourcesInventorySourcesHostsDeleteForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *InventorySourcesInventorySourcesHostsDeleteForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/inventory_sources/{id}/hosts/][%d] inventorySourcesInventorySourcesHostsDeleteForbidden ", 403)
}

func (o *InventorySourcesInventorySourcesHostsDeleteForbidden) String() string {
	return fmt.Sprintf("[DELETE /api/v2/inventory_sources/{id}/hosts/][%d] inventorySourcesInventorySourcesHostsDeleteForbidden ", 403)
}

func (o *InventorySourcesInventorySourcesHostsDeleteForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
