// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GroupsGroupsListReader is a Reader for the GroupsGroupsList structure.
type GroupsGroupsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupsGroupsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupsGroupsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGroupsGroupsListOK creates a GroupsGroupsListOK with default headers values
func NewGroupsGroupsListOK() *GroupsGroupsListOK {
	return &GroupsGroupsListOK{}
}

/*
GroupsGroupsListOK describes a response with status code 200, with default header values.

GroupsGroupsListOK groups groups list o k
*/
type GroupsGroupsListOK struct {
}

// IsSuccess returns true when this groups groups list o k response has a 2xx status code
func (o *GroupsGroupsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this groups groups list o k response has a 3xx status code
func (o *GroupsGroupsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this groups groups list o k response has a 4xx status code
func (o *GroupsGroupsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this groups groups list o k response has a 5xx status code
func (o *GroupsGroupsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this groups groups list o k response a status code equal to that given
func (o *GroupsGroupsListOK) IsCode(code int) bool {
	return code == 200
}

func (o *GroupsGroupsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/][%d] groupsGroupsListOK ", 200)
}

func (o *GroupsGroupsListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/groups/][%d] groupsGroupsListOK ", 200)
}

func (o *GroupsGroupsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
