// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OrganizationsOrganizationsAccessListListReader is a Reader for the OrganizationsOrganizationsAccessListList structure.
type OrganizationsOrganizationsAccessListListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationsOrganizationsAccessListListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrganizationsOrganizationsAccessListListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOrganizationsOrganizationsAccessListListOK creates a OrganizationsOrganizationsAccessListListOK with default headers values
func NewOrganizationsOrganizationsAccessListListOK() *OrganizationsOrganizationsAccessListListOK {
	return &OrganizationsOrganizationsAccessListListOK{}
}

/*
OrganizationsOrganizationsAccessListListOK describes a response with status code 200, with default header values.

OrganizationsOrganizationsAccessListListOK organizations organizations access list list o k
*/
type OrganizationsOrganizationsAccessListListOK struct {
}

// IsSuccess returns true when this organizations organizations access list list o k response has a 2xx status code
func (o *OrganizationsOrganizationsAccessListListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this organizations organizations access list list o k response has a 3xx status code
func (o *OrganizationsOrganizationsAccessListListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organizations organizations access list list o k response has a 4xx status code
func (o *OrganizationsOrganizationsAccessListListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this organizations organizations access list list o k response has a 5xx status code
func (o *OrganizationsOrganizationsAccessListListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this organizations organizations access list list o k response a status code equal to that given
func (o *OrganizationsOrganizationsAccessListListOK) IsCode(code int) bool {
	return code == 200
}

func (o *OrganizationsOrganizationsAccessListListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{id}/access_list/][%d] organizationsOrganizationsAccessListListOK ", 200)
}

func (o *OrganizationsOrganizationsAccessListListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{id}/access_list/][%d] organizationsOrganizationsAccessListListOK ", 200)
}

func (o *OrganizationsOrganizationsAccessListListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
