// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrganizationsOrganizationsJobTemplatesCreateReader is a Reader for the OrganizationsOrganizationsJobTemplatesCreate structure.
type OrganizationsOrganizationsJobTemplatesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationsOrganizationsJobTemplatesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewOrganizationsOrganizationsJobTemplatesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOrganizationsOrganizationsJobTemplatesCreateCreated creates a OrganizationsOrganizationsJobTemplatesCreateCreated with default headers values
func NewOrganizationsOrganizationsJobTemplatesCreateCreated() *OrganizationsOrganizationsJobTemplatesCreateCreated {
	return &OrganizationsOrganizationsJobTemplatesCreateCreated{}
}

/*
OrganizationsOrganizationsJobTemplatesCreateCreated describes a response with status code 201, with default header values.

OrganizationsOrganizationsJobTemplatesCreateCreated organizations organizations job templates create created
*/
type OrganizationsOrganizationsJobTemplatesCreateCreated struct {
}

// IsSuccess returns true when this organizations organizations job templates create created response has a 2xx status code
func (o *OrganizationsOrganizationsJobTemplatesCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this organizations organizations job templates create created response has a 3xx status code
func (o *OrganizationsOrganizationsJobTemplatesCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organizations organizations job templates create created response has a 4xx status code
func (o *OrganizationsOrganizationsJobTemplatesCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this organizations organizations job templates create created response has a 5xx status code
func (o *OrganizationsOrganizationsJobTemplatesCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this organizations organizations job templates create created response a status code equal to that given
func (o *OrganizationsOrganizationsJobTemplatesCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *OrganizationsOrganizationsJobTemplatesCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/organizations/{id}/job_templates/][%d] organizationsOrganizationsJobTemplatesCreateCreated ", 201)
}

func (o *OrganizationsOrganizationsJobTemplatesCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/organizations/{id}/job_templates/][%d] organizationsOrganizationsJobTemplatesCreateCreated ", 201)
}

func (o *OrganizationsOrganizationsJobTemplatesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
OrganizationsOrganizationsJobTemplatesCreateBody organizations organizations job templates create body
swagger:model OrganizationsOrganizationsJobTemplatesCreateBody
*/
type OrganizationsOrganizationsJobTemplatesCreateBody struct {

	// allow simultaneous
	AllowSimultaneous bool `json:"allow_simultaneous,omitempty"`

	// ask credential on launch
	AskCredentialOnLaunch bool `json:"ask_credential_on_launch,omitempty"`

	// ask diff mode on launch
	AskDiffModeOnLaunch bool `json:"ask_diff_mode_on_launch,omitempty"`

	// ask inventory on launch
	AskInventoryOnLaunch bool `json:"ask_inventory_on_launch,omitempty"`

	// ask job type on launch
	AskJobTypeOnLaunch bool `json:"ask_job_type_on_launch,omitempty"`

	// ask limit on launch
	AskLimitOnLaunch bool `json:"ask_limit_on_launch,omitempty"`

	// ask scm branch on launch
	AskScmBranchOnLaunch bool `json:"ask_scm_branch_on_launch,omitempty"`

	// ask skip tags on launch
	AskSkipTagsOnLaunch bool `json:"ask_skip_tags_on_launch,omitempty"`

	// ask tags on launch
	AskTagsOnLaunch bool `json:"ask_tags_on_launch,omitempty"`

	// ask variables on launch
	AskVariablesOnLaunch bool `json:"ask_variables_on_launch,omitempty"`

	// ask verbosity on launch
	AskVerbosityOnLaunch bool `json:"ask_verbosity_on_launch,omitempty"`

	// become enabled
	BecomeEnabled bool `json:"become_enabled,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// If enabled, textual changes made to any templated files on the host are shown in the standard output
	DiffMode bool `json:"diff_mode,omitempty"`

	// The container image to be used for execution.
	ExecutionEnvironment int64 `json:"execution_environment,omitempty"`

	// extra vars
	ExtraVars string `json:"extra_vars,omitempty"`

	// force handlers
	ForceHandlers bool `json:"force_handlers,omitempty"`

	// forks
	Forks int64 `json:"forks,omitempty"`

	// host config key
	HostConfigKey string `json:"host_config_key,omitempty"`

	// inventory
	Inventory int64 `json:"inventory,omitempty"`

	// The number of jobs to slice into at runtime. Will cause the Job Template to launch a workflow if value is greater than 1.
	JobSliceCount int64 `json:"job_slice_count,omitempty"`

	// job tags
	JobTags string `json:"job_tags,omitempty"`

	// job type
	JobType string `json:"job_type,omitempty"`

	// limit
	Limit string `json:"limit,omitempty"`

	// name
	// Required: true
	Name *string `json:"name"`

	// playbook
	Playbook string `json:"playbook,omitempty"`

	// project
	Project string `json:"project,omitempty"`

	// Branch to use in job run. Project default used if blank. Only allowed if project allow_override field is set to true.
	ScmBranch string `json:"scm_branch,omitempty"`

	// skip tags
	SkipTags string `json:"skip_tags,omitempty"`

	// start at task
	StartAtTask string `json:"start_at_task,omitempty"`

	// survey enabled
	SurveyEnabled bool `json:"survey_enabled,omitempty"`

	// The amount of time (in seconds) to run before the task is canceled.
	Timeout int64 `json:"timeout,omitempty"`

	// If enabled, the service will act as an Ansible Fact Cache Plugin; persisting facts at the end of a playbook run to the database and caching facts for use by Ansible.
	UseFactCache bool `json:"use_fact_cache,omitempty"`

	// verbosity
	Verbosity string `json:"verbosity,omitempty"`

	// Personal Access Token for posting back the status to the service API
	WebhookCredential int64 `json:"webhook_credential,omitempty"`

	// Service that webhook requests will be accepted from
	WebhookService string `json:"webhook_service,omitempty"`
}

// Validate validates this organizations organizations job templates create body
func (o *OrganizationsOrganizationsJobTemplatesCreateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *OrganizationsOrganizationsJobTemplatesCreateBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this organizations organizations job templates create body based on context it is used
func (o *OrganizationsOrganizationsJobTemplatesCreateBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *OrganizationsOrganizationsJobTemplatesCreateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *OrganizationsOrganizationsJobTemplatesCreateBody) UnmarshalBinary(b []byte) error {
	var res OrganizationsOrganizationsJobTemplatesCreateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
