// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OrganizationsOrganizationsNotificationTemplatesErrorListReader is a Reader for the OrganizationsOrganizationsNotificationTemplatesErrorList structure.
type OrganizationsOrganizationsNotificationTemplatesErrorListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationsOrganizationsNotificationTemplatesErrorListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrganizationsOrganizationsNotificationTemplatesErrorListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOrganizationsOrganizationsNotificationTemplatesErrorListOK creates a OrganizationsOrganizationsNotificationTemplatesErrorListOK with default headers values
func NewOrganizationsOrganizationsNotificationTemplatesErrorListOK() *OrganizationsOrganizationsNotificationTemplatesErrorListOK {
	return &OrganizationsOrganizationsNotificationTemplatesErrorListOK{}
}

/*
OrganizationsOrganizationsNotificationTemplatesErrorListOK describes a response with status code 200, with default header values.

OrganizationsOrganizationsNotificationTemplatesErrorListOK organizations organizations notification templates error list o k
*/
type OrganizationsOrganizationsNotificationTemplatesErrorListOK struct {
}

// IsSuccess returns true when this organizations organizations notification templates error list o k response has a 2xx status code
func (o *OrganizationsOrganizationsNotificationTemplatesErrorListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this organizations organizations notification templates error list o k response has a 3xx status code
func (o *OrganizationsOrganizationsNotificationTemplatesErrorListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organizations organizations notification templates error list o k response has a 4xx status code
func (o *OrganizationsOrganizationsNotificationTemplatesErrorListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this organizations organizations notification templates error list o k response has a 5xx status code
func (o *OrganizationsOrganizationsNotificationTemplatesErrorListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this organizations organizations notification templates error list o k response a status code equal to that given
func (o *OrganizationsOrganizationsNotificationTemplatesErrorListOK) IsCode(code int) bool {
	return code == 200
}

func (o *OrganizationsOrganizationsNotificationTemplatesErrorListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{id}/notification_templates_error/][%d] organizationsOrganizationsNotificationTemplatesErrorListOK ", 200)
}

func (o *OrganizationsOrganizationsNotificationTemplatesErrorListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{id}/notification_templates_error/][%d] organizationsOrganizationsNotificationTemplatesErrorListOK ", 200)
}

func (o *OrganizationsOrganizationsNotificationTemplatesErrorListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
