// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrganizationsOrganizationsTeamsCreateReader is a Reader for the OrganizationsOrganizationsTeamsCreate structure.
type OrganizationsOrganizationsTeamsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationsOrganizationsTeamsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewOrganizationsOrganizationsTeamsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOrganizationsOrganizationsTeamsCreateCreated creates a OrganizationsOrganizationsTeamsCreateCreated with default headers values
func NewOrganizationsOrganizationsTeamsCreateCreated() *OrganizationsOrganizationsTeamsCreateCreated {
	return &OrganizationsOrganizationsTeamsCreateCreated{}
}

/*
OrganizationsOrganizationsTeamsCreateCreated describes a response with status code 201, with default header values.

OrganizationsOrganizationsTeamsCreateCreated organizations organizations teams create created
*/
type OrganizationsOrganizationsTeamsCreateCreated struct {
}

// IsSuccess returns true when this organizations organizations teams create created response has a 2xx status code
func (o *OrganizationsOrganizationsTeamsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this organizations organizations teams create created response has a 3xx status code
func (o *OrganizationsOrganizationsTeamsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organizations organizations teams create created response has a 4xx status code
func (o *OrganizationsOrganizationsTeamsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this organizations organizations teams create created response has a 5xx status code
func (o *OrganizationsOrganizationsTeamsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this organizations organizations teams create created response a status code equal to that given
func (o *OrganizationsOrganizationsTeamsCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *OrganizationsOrganizationsTeamsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/organizations/{id}/teams/][%d] organizationsOrganizationsTeamsCreateCreated ", 201)
}

func (o *OrganizationsOrganizationsTeamsCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/organizations/{id}/teams/][%d] organizationsOrganizationsTeamsCreateCreated ", 201)
}

func (o *OrganizationsOrganizationsTeamsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
OrganizationsOrganizationsTeamsCreateBody organizations organizations teams create body
swagger:model OrganizationsOrganizationsTeamsCreateBody
*/
type OrganizationsOrganizationsTeamsCreateBody struct {

	// description
	Description string `json:"description,omitempty"`

	// name
	// Required: true
	Name *string `json:"name"`

	// organization
	// Required: true
	Organization *int64 `json:"organization"`
}

// Validate validates this organizations organizations teams create body
func (o *OrganizationsOrganizationsTeamsCreateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateOrganization(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *OrganizationsOrganizationsTeamsCreateBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

func (o *OrganizationsOrganizationsTeamsCreateBody) validateOrganization(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"organization", "body", o.Organization); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this organizations organizations teams create body based on context it is used
func (o *OrganizationsOrganizationsTeamsCreateBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *OrganizationsOrganizationsTeamsCreateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *OrganizationsOrganizationsTeamsCreateBody) UnmarshalBinary(b []byte) error {
	var res OrganizationsOrganizationsTeamsCreateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
