// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OrganizationsOrganizationsAdminsListReader is a Reader for the OrganizationsOrganizationsAdminsList structure.
type OrganizationsOrganizationsAdminsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationsOrganizationsAdminsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrganizationsOrganizationsAdminsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOrganizationsOrganizationsAdminsListOK creates a OrganizationsOrganizationsAdminsListOK with default headers values
func NewOrganizationsOrganizationsAdminsListOK() *OrganizationsOrganizationsAdminsListOK {
	return &OrganizationsOrganizationsAdminsListOK{}
}

/*
OrganizationsOrganizationsAdminsListOK describes a response with status code 200, with default header values.

OrganizationsOrganizationsAdminsListOK organizations organizations admins list o k
*/
type OrganizationsOrganizationsAdminsListOK struct {
}

// IsSuccess returns true when this organizations organizations admins list o k response has a 2xx status code
func (o *OrganizationsOrganizationsAdminsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this organizations organizations admins list o k response has a 3xx status code
func (o *OrganizationsOrganizationsAdminsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organizations organizations admins list o k response has a 4xx status code
func (o *OrganizationsOrganizationsAdminsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this organizations organizations admins list o k response has a 5xx status code
func (o *OrganizationsOrganizationsAdminsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this organizations organizations admins list o k response a status code equal to that given
func (o *OrganizationsOrganizationsAdminsListOK) IsCode(code int) bool {
	return code == 200
}

func (o *OrganizationsOrganizationsAdminsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{id}/admins/][%d] organizationsOrganizationsAdminsListOK ", 200)
}

func (o *OrganizationsOrganizationsAdminsListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{id}/admins/][%d] organizationsOrganizationsAdminsListOK ", 200)
}

func (o *OrganizationsOrganizationsAdminsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
