// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OrganizationsOrganizationsNotificationTemplatesStartedCreateReader is a Reader for the OrganizationsOrganizationsNotificationTemplatesStartedCreate structure.
type OrganizationsOrganizationsNotificationTemplatesStartedCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationsOrganizationsNotificationTemplatesStartedCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewOrganizationsOrganizationsNotificationTemplatesStartedCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOrganizationsOrganizationsNotificationTemplatesStartedCreateCreated creates a OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated with default headers values
func NewOrganizationsOrganizationsNotificationTemplatesStartedCreateCreated() *OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated {
	return &OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated{}
}

/*
OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated describes a response with status code 201, with default header values.

OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated organizations organizations notification templates started create created
*/
type OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated struct {
}

// IsSuccess returns true when this organizations organizations notification templates started create created response has a 2xx status code
func (o *OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this organizations organizations notification templates started create created response has a 3xx status code
func (o *OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organizations organizations notification templates started create created response has a 4xx status code
func (o *OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this organizations organizations notification templates started create created response has a 5xx status code
func (o *OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this organizations organizations notification templates started create created response a status code equal to that given
func (o *OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/organizations/{id}/notification_templates_started/][%d] organizationsOrganizationsNotificationTemplatesStartedCreateCreated ", 201)
}

func (o *OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/organizations/{id}/notification_templates_started/][%d] organizationsOrganizationsNotificationTemplatesStartedCreateCreated ", 201)
}

func (o *OrganizationsOrganizationsNotificationTemplatesStartedCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
