// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OrganizationsOrganizationsApplicationsListReader is a Reader for the OrganizationsOrganizationsApplicationsList structure.
type OrganizationsOrganizationsApplicationsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationsOrganizationsApplicationsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrganizationsOrganizationsApplicationsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOrganizationsOrganizationsApplicationsListOK creates a OrganizationsOrganizationsApplicationsListOK with default headers values
func NewOrganizationsOrganizationsApplicationsListOK() *OrganizationsOrganizationsApplicationsListOK {
	return &OrganizationsOrganizationsApplicationsListOK{}
}

/*
OrganizationsOrganizationsApplicationsListOK describes a response with status code 200, with default header values.

OrganizationsOrganizationsApplicationsListOK organizations organizations applications list o k
*/
type OrganizationsOrganizationsApplicationsListOK struct {
}

// IsSuccess returns true when this organizations organizations applications list o k response has a 2xx status code
func (o *OrganizationsOrganizationsApplicationsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this organizations organizations applications list o k response has a 3xx status code
func (o *OrganizationsOrganizationsApplicationsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organizations organizations applications list o k response has a 4xx status code
func (o *OrganizationsOrganizationsApplicationsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this organizations organizations applications list o k response has a 5xx status code
func (o *OrganizationsOrganizationsApplicationsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this organizations organizations applications list o k response a status code equal to that given
func (o *OrganizationsOrganizationsApplicationsListOK) IsCode(code int) bool {
	return code == 200
}

func (o *OrganizationsOrganizationsApplicationsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{id}/applications/][%d] organizationsOrganizationsApplicationsListOK ", 200)
}

func (o *OrganizationsOrganizationsApplicationsListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{id}/applications/][%d] organizationsOrganizationsApplicationsListOK ", 200)
}

func (o *OrganizationsOrganizationsApplicationsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
