// Code generated by go-swagger; DO NOT EDIT.

package settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SettingsSettingsUpdateReader is a Reader for the SettingsSettingsUpdate structure.
type SettingsSettingsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SettingsSettingsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSettingsSettingsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSettingsSettingsUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSettingsSettingsUpdateOK creates a SettingsSettingsUpdateOK with default headers values
func NewSettingsSettingsUpdateOK() *SettingsSettingsUpdateOK {
	return &SettingsSettingsUpdateOK{}
}

/*
SettingsSettingsUpdateOK describes a response with status code 200, with default header values.

SettingsSettingsUpdateOK settings settings update o k
*/
type SettingsSettingsUpdateOK struct {
}

// IsSuccess returns true when this settings settings update o k response has a 2xx status code
func (o *SettingsSettingsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this settings settings update o k response has a 3xx status code
func (o *SettingsSettingsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this settings settings update o k response has a 4xx status code
func (o *SettingsSettingsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this settings settings update o k response has a 5xx status code
func (o *SettingsSettingsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this settings settings update o k response a status code equal to that given
func (o *SettingsSettingsUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *SettingsSettingsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /api/v2/settings/{category_slug}/][%d] settingsSettingsUpdateOK ", 200)
}

func (o *SettingsSettingsUpdateOK) String() string {
	return fmt.Sprintf("[PUT /api/v2/settings/{category_slug}/][%d] settingsSettingsUpdateOK ", 200)
}

func (o *SettingsSettingsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSettingsSettingsUpdateBadRequest creates a SettingsSettingsUpdateBadRequest with default headers values
func NewSettingsSettingsUpdateBadRequest() *SettingsSettingsUpdateBadRequest {
	return &SettingsSettingsUpdateBadRequest{}
}

/*
SettingsSettingsUpdateBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type SettingsSettingsUpdateBadRequest struct {
}

// IsSuccess returns true when this settings settings update bad request response has a 2xx status code
func (o *SettingsSettingsUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this settings settings update bad request response has a 3xx status code
func (o *SettingsSettingsUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this settings settings update bad request response has a 4xx status code
func (o *SettingsSettingsUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this settings settings update bad request response has a 5xx status code
func (o *SettingsSettingsUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this settings settings update bad request response a status code equal to that given
func (o *SettingsSettingsUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *SettingsSettingsUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v2/settings/{category_slug}/][%d] settingsSettingsUpdateBadRequest ", 400)
}

func (o *SettingsSettingsUpdateBadRequest) String() string {
	return fmt.Sprintf("[PUT /api/v2/settings/{category_slug}/][%d] settingsSettingsUpdateBadRequest ", 400)
}

func (o *SettingsSettingsUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
