// Code generated by go-swagger; DO NOT EDIT.

package system_jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSystemJobsSystemJobsDeleteParams creates a new SystemJobsSystemJobsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSystemJobsSystemJobsDeleteParams() *SystemJobsSystemJobsDeleteParams {
	return &SystemJobsSystemJobsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSystemJobsSystemJobsDeleteParamsWithTimeout creates a new SystemJobsSystemJobsDeleteParams object
// with the ability to set a timeout on a request.
func NewSystemJobsSystemJobsDeleteParamsWithTimeout(timeout time.Duration) *SystemJobsSystemJobsDeleteParams {
	return &SystemJobsSystemJobsDeleteParams{
		timeout: timeout,
	}
}

// NewSystemJobsSystemJobsDeleteParamsWithContext creates a new SystemJobsSystemJobsDeleteParams object
// with the ability to set a context for a request.
func NewSystemJobsSystemJobsDeleteParamsWithContext(ctx context.Context) *SystemJobsSystemJobsDeleteParams {
	return &SystemJobsSystemJobsDeleteParams{
		Context: ctx,
	}
}

// NewSystemJobsSystemJobsDeleteParamsWithHTTPClient creates a new SystemJobsSystemJobsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewSystemJobsSystemJobsDeleteParamsWithHTTPClient(client *http.Client) *SystemJobsSystemJobsDeleteParams {
	return &SystemJobsSystemJobsDeleteParams{
		HTTPClient: client,
	}
}

/*
SystemJobsSystemJobsDeleteParams contains all the parameters to send to the API endpoint

	for the system jobs system jobs delete operation.

	Typically these are written to a http.Request.
*/
type SystemJobsSystemJobsDeleteParams struct {

	// ID.
	ID string

	/* Search.

	   A search term.
	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the system jobs system jobs delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemJobsSystemJobsDeleteParams) WithDefaults() *SystemJobsSystemJobsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the system jobs system jobs delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemJobsSystemJobsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the system jobs system jobs delete params
func (o *SystemJobsSystemJobsDeleteParams) WithTimeout(timeout time.Duration) *SystemJobsSystemJobsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the system jobs system jobs delete params
func (o *SystemJobsSystemJobsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the system jobs system jobs delete params
func (o *SystemJobsSystemJobsDeleteParams) WithContext(ctx context.Context) *SystemJobsSystemJobsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the system jobs system jobs delete params
func (o *SystemJobsSystemJobsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the system jobs system jobs delete params
func (o *SystemJobsSystemJobsDeleteParams) WithHTTPClient(client *http.Client) *SystemJobsSystemJobsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the system jobs system jobs delete params
func (o *SystemJobsSystemJobsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the system jobs system jobs delete params
func (o *SystemJobsSystemJobsDeleteParams) WithID(id string) *SystemJobsSystemJobsDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the system jobs system jobs delete params
func (o *SystemJobsSystemJobsDeleteParams) SetID(id string) {
	o.ID = id
}

// WithSearch adds the search to the system jobs system jobs delete params
func (o *SystemJobsSystemJobsDeleteParams) WithSearch(search *string) *SystemJobsSystemJobsDeleteParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the system jobs system jobs delete params
func (o *SystemJobsSystemJobsDeleteParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *SystemJobsSystemJobsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
