// Code generated by go-swagger; DO NOT EDIT.

package system_job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListReader is a Reader for the SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedList structure.
type SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK creates a SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK with default headers values
func NewSystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK() *SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK {
	return &SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK{}
}

/*
SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK describes a response with status code 200, with default header values.

SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK system job templates system job templates notification templates started list o k
*/
type SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK struct {
}

// IsSuccess returns true when this system job templates system job templates notification templates started list o k response has a 2xx status code
func (o *SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this system job templates system job templates notification templates started list o k response has a 3xx status code
func (o *SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system job templates system job templates notification templates started list o k response has a 4xx status code
func (o *SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this system job templates system job templates notification templates started list o k response has a 5xx status code
func (o *SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this system job templates system job templates notification templates started list o k response a status code equal to that given
func (o *SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK) IsCode(code int) bool {
	return code == 200
}

func (o *SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/system_job_templates/{id}/notification_templates_started/][%d] systemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK ", 200)
}

func (o *SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/system_job_templates/{id}/notification_templates_started/][%d] systemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK ", 200)
}

func (o *SystemJobTemplatesSystemJobTemplatesNotificationTemplatesStartedListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
