// Code generated by go-swagger; DO NOT EDIT.

package job_host_summaries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new job host summaries API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for job host summaries API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	JobHostSummariesJobHostSummariesRead(params *JobHostSummariesJobHostSummariesReadParams, opts ...ClientOption) (*JobHostSummariesJobHostSummariesReadOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
	JobHostSummariesJobHostSummariesRead retrieves a job host summary

Make GET request to this resource to retrieve a single job host summary
record containing the following fields:

* `id`: Database ID for this job host summary. (integer)
* `type`: Data type for this job host summary. (choice)
* `url`: URL for this job host summary. (string)
* `related`: Data structure with URLs of related resources. (object)
* `summary_fields`: Data structure with name/description for related resources.  The output for some objects may be limited for performance reasons. (object)
* `created`: Timestamp when this job host summary was created. (datetime)
* `modified`: Timestamp when this job host summary was last modified. (datetime)
* `job`:  (id)
* `host`:  (id)
* `host_name`:  (string)
* `changed`:  (integer)
* `dark`:  (integer)
* `failures`:  (integer)
* `ok`:  (integer)
* `processed`:  (integer)
* `skipped`:  (integer)
* `failed`:  (boolean)
* `ignored`:  (integer)
* `rescued`:  (integer)
*/
func (a *Client) JobHostSummariesJobHostSummariesRead(params *JobHostSummariesJobHostSummariesReadParams, opts ...ClientOption) (*JobHostSummariesJobHostSummariesReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewJobHostSummariesJobHostSummariesReadParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Job Host Summaries_job_host_summaries_read",
		Method:             "GET",
		PathPattern:        "/api/v2/job_host_summaries/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &JobHostSummariesJobHostSummariesReadReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*JobHostSummariesJobHostSummariesReadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Job Host Summaries_job_host_summaries_read: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
