// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GroupsGroupsActivityStreamListReader is a Reader for the GroupsGroupsActivityStreamList structure.
type GroupsGroupsActivityStreamListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupsGroupsActivityStreamListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupsGroupsActivityStreamListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGroupsGroupsActivityStreamListOK creates a GroupsGroupsActivityStreamListOK with default headers values
func NewGroupsGroupsActivityStreamListOK() *GroupsGroupsActivityStreamListOK {
	return &GroupsGroupsActivityStreamListOK{}
}

/*
GroupsGroupsActivityStreamListOK describes a response with status code 200, with default header values.

GroupsGroupsActivityStreamListOK groups groups activity stream list o k
*/
type GroupsGroupsActivityStreamListOK struct {
}

// IsSuccess returns true when this groups groups activity stream list o k response has a 2xx status code
func (o *GroupsGroupsActivityStreamListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this groups groups activity stream list o k response has a 3xx status code
func (o *GroupsGroupsActivityStreamListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this groups groups activity stream list o k response has a 4xx status code
func (o *GroupsGroupsActivityStreamListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this groups groups activity stream list o k response has a 5xx status code
func (o *GroupsGroupsActivityStreamListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this groups groups activity stream list o k response a status code equal to that given
func (o *GroupsGroupsActivityStreamListOK) IsCode(code int) bool {
	return code == 200
}

func (o *GroupsGroupsActivityStreamListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/{id}/activity_stream/][%d] groupsGroupsActivityStreamListOK ", 200)
}

func (o *GroupsGroupsActivityStreamListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/groups/{id}/activity_stream/][%d] groupsGroupsActivityStreamListOK ", 200)
}

func (o *GroupsGroupsActivityStreamListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
