// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GroupsGroupsReadReader is a Reader for the GroupsGroupsRead structure.
type GroupsGroupsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupsGroupsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupsGroupsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGroupsGroupsReadOK creates a GroupsGroupsReadOK with default headers values
func NewGroupsGroupsReadOK() *GroupsGroupsReadOK {
	return &GroupsGroupsReadOK{}
}

/*
GroupsGroupsReadOK describes a response with status code 200, with default header values.

GroupsGroupsReadOK groups groups read o k
*/
type GroupsGroupsReadOK struct {
}

// IsSuccess returns true when this groups groups read o k response has a 2xx status code
func (o *GroupsGroupsReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this groups groups read o k response has a 3xx status code
func (o *GroupsGroupsReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this groups groups read o k response has a 4xx status code
func (o *GroupsGroupsReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this groups groups read o k response has a 5xx status code
func (o *GroupsGroupsReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this groups groups read o k response a status code equal to that given
func (o *GroupsGroupsReadOK) IsCode(code int) bool {
	return code == 200
}

func (o *GroupsGroupsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/{id}/][%d] groupsGroupsReadOK ", 200)
}

func (o *GroupsGroupsReadOK) String() string {
	return fmt.Sprintf("[GET /api/v2/groups/{id}/][%d] groupsGroupsReadOK ", 200)
}

func (o *GroupsGroupsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
