// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OrganizationsOrganizationsCredentialsListReader is a Reader for the OrganizationsOrganizationsCredentialsList structure.
type OrganizationsOrganizationsCredentialsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationsOrganizationsCredentialsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrganizationsOrganizationsCredentialsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOrganizationsOrganizationsCredentialsListOK creates a OrganizationsOrganizationsCredentialsListOK with default headers values
func NewOrganizationsOrganizationsCredentialsListOK() *OrganizationsOrganizationsCredentialsListOK {
	return &OrganizationsOrganizationsCredentialsListOK{}
}

/*
OrganizationsOrganizationsCredentialsListOK describes a response with status code 200, with default header values.

OrganizationsOrganizationsCredentialsListOK organizations organizations credentials list o k
*/
type OrganizationsOrganizationsCredentialsListOK struct {
}

// IsSuccess returns true when this organizations organizations credentials list o k response has a 2xx status code
func (o *OrganizationsOrganizationsCredentialsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this organizations organizations credentials list o k response has a 3xx status code
func (o *OrganizationsOrganizationsCredentialsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organizations organizations credentials list o k response has a 4xx status code
func (o *OrganizationsOrganizationsCredentialsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this organizations organizations credentials list o k response has a 5xx status code
func (o *OrganizationsOrganizationsCredentialsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this organizations organizations credentials list o k response a status code equal to that given
func (o *OrganizationsOrganizationsCredentialsListOK) IsCode(code int) bool {
	return code == 200
}

func (o *OrganizationsOrganizationsCredentialsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{id}/credentials/][%d] organizationsOrganizationsCredentialsListOK ", 200)
}

func (o *OrganizationsOrganizationsCredentialsListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{id}/credentials/][%d] organizationsOrganizationsCredentialsListOK ", 200)
}

func (o *OrganizationsOrganizationsCredentialsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
