// Code generated by go-swagger; DO NOT EDIT.

package execution_environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListReader is a Reader for the ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesList structure.
type ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK creates a ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK with default headers values
func NewExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK() *ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK {
	return &ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK{}
}

/*
ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK describes a response with status code 200, with default header values.

ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK execution environments execution environments unified job templates list o k
*/
type ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK struct {
}

// IsSuccess returns true when this execution environments execution environments unified job templates list o k response has a 2xx status code
func (o *ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this execution environments execution environments unified job templates list o k response has a 3xx status code
func (o *ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this execution environments execution environments unified job templates list o k response has a 4xx status code
func (o *ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this execution environments execution environments unified job templates list o k response has a 5xx status code
func (o *ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this execution environments execution environments unified job templates list o k response a status code equal to that given
func (o *ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK) IsCode(code int) bool {
	return code == 200
}

func (o *ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/execution_environments/{id}/unified_job_templates/][%d] executionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK ", 200)
}

func (o *ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/execution_environments/{id}/unified_job_templates/][%d] executionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK ", 200)
}

func (o *ExecutionEnvironmentsExecutionEnvironmentsUnifiedJobTemplatesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
