// Code generated by go-swagger; DO NOT EDIT.

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// JobsJobsDeleteReader is a Reader for the JobsJobsDelete structure.
type JobsJobsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobsJobsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewJobsJobsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewJobsJobsDeleteForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewJobsJobsDeleteNoContent creates a JobsJobsDeleteNoContent with default headers values
func NewJobsJobsDeleteNoContent() *JobsJobsDeleteNoContent {
	return &JobsJobsDeleteNoContent{}
}

/*
JobsJobsDeleteNoContent describes a response with status code 204, with default header values.

JobsJobsDeleteNoContent jobs jobs delete no content
*/
type JobsJobsDeleteNoContent struct {
}

// IsSuccess returns true when this jobs jobs delete no content response has a 2xx status code
func (o *JobsJobsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this jobs jobs delete no content response has a 3xx status code
func (o *JobsJobsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this jobs jobs delete no content response has a 4xx status code
func (o *JobsJobsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this jobs jobs delete no content response has a 5xx status code
func (o *JobsJobsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this jobs jobs delete no content response a status code equal to that given
func (o *JobsJobsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *JobsJobsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/jobs/{id}/][%d] jobsJobsDeleteNoContent ", 204)
}

func (o *JobsJobsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/v2/jobs/{id}/][%d] jobsJobsDeleteNoContent ", 204)
}

func (o *JobsJobsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewJobsJobsDeleteForbidden creates a JobsJobsDeleteForbidden with default headers values
func NewJobsJobsDeleteForbidden() *JobsJobsDeleteForbidden {
	return &JobsJobsDeleteForbidden{}
}

/*
JobsJobsDeleteForbidden describes a response with status code 403, with default header values.

forbidden
*/
type JobsJobsDeleteForbidden struct {
}

// IsSuccess returns true when this jobs jobs delete forbidden response has a 2xx status code
func (o *JobsJobsDeleteForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this jobs jobs delete forbidden response has a 3xx status code
func (o *JobsJobsDeleteForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this jobs jobs delete forbidden response has a 4xx status code
func (o *JobsJobsDeleteForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this jobs jobs delete forbidden response has a 5xx status code
func (o *JobsJobsDeleteForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this jobs jobs delete forbidden response a status code equal to that given
func (o *JobsJobsDeleteForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *JobsJobsDeleteForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/jobs/{id}/][%d] jobsJobsDeleteForbidden ", 403)
}

func (o *JobsJobsDeleteForbidden) String() string {
	return fmt.Sprintf("[DELETE /api/v2/jobs/{id}/][%d] jobsJobsDeleteForbidden ", 403)
}

func (o *JobsJobsDeleteForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
