// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// MetricsMetricsListReader is a Reader for the MetricsMetricsList structure.
type MetricsMetricsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MetricsMetricsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMetricsMetricsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewMetricsMetricsListOK creates a MetricsMetricsListOK with default headers values
func NewMetricsMetricsListOK() *MetricsMetricsListOK {
	return &MetricsMetricsListOK{}
}

/*
MetricsMetricsListOK describes a response with status code 200, with default header values.

MetricsMetricsListOK metrics metrics list o k
*/
type MetricsMetricsListOK struct {
}

// IsSuccess returns true when this metrics metrics list o k response has a 2xx status code
func (o *MetricsMetricsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this metrics metrics list o k response has a 3xx status code
func (o *MetricsMetricsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this metrics metrics list o k response has a 4xx status code
func (o *MetricsMetricsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this metrics metrics list o k response has a 5xx status code
func (o *MetricsMetricsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this metrics metrics list o k response a status code equal to that given
func (o *MetricsMetricsListOK) IsCode(code int) bool {
	return code == 200
}

func (o *MetricsMetricsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/metrics/][%d] metricsMetricsListOK ", 200)
}

func (o *MetricsMetricsListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/metrics/][%d] metricsMetricsListOK ", 200)
}

func (o *MetricsMetricsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
