// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// HostsHostsAdHocCommandsListReader is a Reader for the HostsHostsAdHocCommandsList structure.
type HostsHostsAdHocCommandsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HostsHostsAdHocCommandsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHostsHostsAdHocCommandsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewHostsHostsAdHocCommandsListOK creates a HostsHostsAdHocCommandsListOK with default headers values
func NewHostsHostsAdHocCommandsListOK() *HostsHostsAdHocCommandsListOK {
	return &HostsHostsAdHocCommandsListOK{}
}

/*
HostsHostsAdHocCommandsListOK describes a response with status code 200, with default header values.

HostsHostsAdHocCommandsListOK hosts hosts ad hoc commands list o k
*/
type HostsHostsAdHocCommandsListOK struct {
}

// IsSuccess returns true when this hosts hosts ad hoc commands list o k response has a 2xx status code
func (o *HostsHostsAdHocCommandsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this hosts hosts ad hoc commands list o k response has a 3xx status code
func (o *HostsHostsAdHocCommandsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this hosts hosts ad hoc commands list o k response has a 4xx status code
func (o *HostsHostsAdHocCommandsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this hosts hosts ad hoc commands list o k response has a 5xx status code
func (o *HostsHostsAdHocCommandsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this hosts hosts ad hoc commands list o k response a status code equal to that given
func (o *HostsHostsAdHocCommandsListOK) IsCode(code int) bool {
	return code == 200
}

func (o *HostsHostsAdHocCommandsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/hosts/{id}/ad_hoc_commands/][%d] hostsHostsAdHocCommandsListOK ", 200)
}

func (o *HostsHostsAdHocCommandsListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/hosts/{id}/ad_hoc_commands/][%d] hostsHostsAdHocCommandsListOK ", 200)
}

func (o *HostsHostsAdHocCommandsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
