// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// HostsHostsGroupsCreateReader is a Reader for the HostsHostsGroupsCreate structure.
type HostsHostsGroupsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HostsHostsGroupsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewHostsHostsGroupsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewHostsHostsGroupsCreateCreated creates a HostsHostsGroupsCreateCreated with default headers values
func NewHostsHostsGroupsCreateCreated() *HostsHostsGroupsCreateCreated {
	return &HostsHostsGroupsCreateCreated{}
}

/*
HostsHostsGroupsCreateCreated describes a response with status code 201, with default header values.

HostsHostsGroupsCreateCreated hosts hosts groups create created
*/
type HostsHostsGroupsCreateCreated struct {
}

// IsSuccess returns true when this hosts hosts groups create created response has a 2xx status code
func (o *HostsHostsGroupsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this hosts hosts groups create created response has a 3xx status code
func (o *HostsHostsGroupsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this hosts hosts groups create created response has a 4xx status code
func (o *HostsHostsGroupsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this hosts hosts groups create created response has a 5xx status code
func (o *HostsHostsGroupsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this hosts hosts groups create created response a status code equal to that given
func (o *HostsHostsGroupsCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *HostsHostsGroupsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/hosts/{id}/groups/][%d] hostsHostsGroupsCreateCreated ", 201)
}

func (o *HostsHostsGroupsCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/hosts/{id}/groups/][%d] hostsHostsGroupsCreateCreated ", 201)
}

func (o *HostsHostsGroupsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
