// Code generated by go-swagger; DO NOT EDIT.

package ad_hoc_commands

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AdHocCommandsAdHocCommandsRelaunchCreateReader is a Reader for the AdHocCommandsAdHocCommandsRelaunchCreate structure.
type AdHocCommandsAdHocCommandsRelaunchCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AdHocCommandsAdHocCommandsRelaunchCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAdHocCommandsAdHocCommandsRelaunchCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAdHocCommandsAdHocCommandsRelaunchCreateCreated creates a AdHocCommandsAdHocCommandsRelaunchCreateCreated with default headers values
func NewAdHocCommandsAdHocCommandsRelaunchCreateCreated() *AdHocCommandsAdHocCommandsRelaunchCreateCreated {
	return &AdHocCommandsAdHocCommandsRelaunchCreateCreated{}
}

/*
AdHocCommandsAdHocCommandsRelaunchCreateCreated describes a response with status code 201, with default header values.

AdHocCommandsAdHocCommandsRelaunchCreateCreated ad hoc commands ad hoc commands relaunch create created
*/
type AdHocCommandsAdHocCommandsRelaunchCreateCreated struct {
}

// IsSuccess returns true when this ad hoc commands ad hoc commands relaunch create created response has a 2xx status code
func (o *AdHocCommandsAdHocCommandsRelaunchCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ad hoc commands ad hoc commands relaunch create created response has a 3xx status code
func (o *AdHocCommandsAdHocCommandsRelaunchCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ad hoc commands ad hoc commands relaunch create created response has a 4xx status code
func (o *AdHocCommandsAdHocCommandsRelaunchCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this ad hoc commands ad hoc commands relaunch create created response has a 5xx status code
func (o *AdHocCommandsAdHocCommandsRelaunchCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this ad hoc commands ad hoc commands relaunch create created response a status code equal to that given
func (o *AdHocCommandsAdHocCommandsRelaunchCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *AdHocCommandsAdHocCommandsRelaunchCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/ad_hoc_commands/{id}/relaunch/][%d] adHocCommandsAdHocCommandsRelaunchCreateCreated ", 201)
}

func (o *AdHocCommandsAdHocCommandsRelaunchCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/ad_hoc_commands/{id}/relaunch/][%d] adHocCommandsAdHocCommandsRelaunchCreateCreated ", 201)
}

func (o *AdHocCommandsAdHocCommandsRelaunchCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
