// Code generated by go-swagger; DO NOT EDIT.

package job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// JobTemplatesJobTemplatesCallbackListReader is a Reader for the JobTemplatesJobTemplatesCallbackList structure.
type JobTemplatesJobTemplatesCallbackListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobTemplatesJobTemplatesCallbackListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJobTemplatesJobTemplatesCallbackListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewJobTemplatesJobTemplatesCallbackListOK creates a JobTemplatesJobTemplatesCallbackListOK with default headers values
func NewJobTemplatesJobTemplatesCallbackListOK() *JobTemplatesJobTemplatesCallbackListOK {
	return &JobTemplatesJobTemplatesCallbackListOK{}
}

/*
JobTemplatesJobTemplatesCallbackListOK describes a response with status code 200, with default header values.

JobTemplatesJobTemplatesCallbackListOK job templates job templates callback list o k
*/
type JobTemplatesJobTemplatesCallbackListOK struct {
}

// IsSuccess returns true when this job templates job templates callback list o k response has a 2xx status code
func (o *JobTemplatesJobTemplatesCallbackListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this job templates job templates callback list o k response has a 3xx status code
func (o *JobTemplatesJobTemplatesCallbackListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this job templates job templates callback list o k response has a 4xx status code
func (o *JobTemplatesJobTemplatesCallbackListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this job templates job templates callback list o k response has a 5xx status code
func (o *JobTemplatesJobTemplatesCallbackListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this job templates job templates callback list o k response a status code equal to that given
func (o *JobTemplatesJobTemplatesCallbackListOK) IsCode(code int) bool {
	return code == 200
}

func (o *JobTemplatesJobTemplatesCallbackListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/job_templates/{id}/callback/][%d] jobTemplatesJobTemplatesCallbackListOK ", 200)
}

func (o *JobTemplatesJobTemplatesCallbackListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/job_templates/{id}/callback/][%d] jobTemplatesJobTemplatesCallbackListOK ", 200)
}

func (o *JobTemplatesJobTemplatesCallbackListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
