// Code generated by go-swagger; DO NOT EDIT.

package job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// JobTemplatesJobTemplatesSurveySpecCreateReader is a Reader for the JobTemplatesJobTemplatesSurveySpecCreate structure.
type JobTemplatesJobTemplatesSurveySpecCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobTemplatesJobTemplatesSurveySpecCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewJobTemplatesJobTemplatesSurveySpecCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewJobTemplatesJobTemplatesSurveySpecCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewJobTemplatesJobTemplatesSurveySpecCreateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewJobTemplatesJobTemplatesSurveySpecCreateCreated creates a JobTemplatesJobTemplatesSurveySpecCreateCreated with default headers values
func NewJobTemplatesJobTemplatesSurveySpecCreateCreated() *JobTemplatesJobTemplatesSurveySpecCreateCreated {
	return &JobTemplatesJobTemplatesSurveySpecCreateCreated{}
}

/*
JobTemplatesJobTemplatesSurveySpecCreateCreated describes a response with status code 201, with default header values.

JobTemplatesJobTemplatesSurveySpecCreateCreated job templates job templates survey spec create created
*/
type JobTemplatesJobTemplatesSurveySpecCreateCreated struct {
}

// IsSuccess returns true when this job templates job templates survey spec create created response has a 2xx status code
func (o *JobTemplatesJobTemplatesSurveySpecCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this job templates job templates survey spec create created response has a 3xx status code
func (o *JobTemplatesJobTemplatesSurveySpecCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this job templates job templates survey spec create created response has a 4xx status code
func (o *JobTemplatesJobTemplatesSurveySpecCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this job templates job templates survey spec create created response has a 5xx status code
func (o *JobTemplatesJobTemplatesSurveySpecCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this job templates job templates survey spec create created response a status code equal to that given
func (o *JobTemplatesJobTemplatesSurveySpecCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *JobTemplatesJobTemplatesSurveySpecCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/job_templates/{id}/survey_spec/][%d] jobTemplatesJobTemplatesSurveySpecCreateCreated ", 201)
}

func (o *JobTemplatesJobTemplatesSurveySpecCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/job_templates/{id}/survey_spec/][%d] jobTemplatesJobTemplatesSurveySpecCreateCreated ", 201)
}

func (o *JobTemplatesJobTemplatesSurveySpecCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewJobTemplatesJobTemplatesSurveySpecCreateBadRequest creates a JobTemplatesJobTemplatesSurveySpecCreateBadRequest with default headers values
func NewJobTemplatesJobTemplatesSurveySpecCreateBadRequest() *JobTemplatesJobTemplatesSurveySpecCreateBadRequest {
	return &JobTemplatesJobTemplatesSurveySpecCreateBadRequest{}
}

/*
JobTemplatesJobTemplatesSurveySpecCreateBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type JobTemplatesJobTemplatesSurveySpecCreateBadRequest struct {
}

// IsSuccess returns true when this job templates job templates survey spec create bad request response has a 2xx status code
func (o *JobTemplatesJobTemplatesSurveySpecCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this job templates job templates survey spec create bad request response has a 3xx status code
func (o *JobTemplatesJobTemplatesSurveySpecCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this job templates job templates survey spec create bad request response has a 4xx status code
func (o *JobTemplatesJobTemplatesSurveySpecCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this job templates job templates survey spec create bad request response has a 5xx status code
func (o *JobTemplatesJobTemplatesSurveySpecCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this job templates job templates survey spec create bad request response a status code equal to that given
func (o *JobTemplatesJobTemplatesSurveySpecCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *JobTemplatesJobTemplatesSurveySpecCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/job_templates/{id}/survey_spec/][%d] jobTemplatesJobTemplatesSurveySpecCreateBadRequest ", 400)
}

func (o *JobTemplatesJobTemplatesSurveySpecCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v2/job_templates/{id}/survey_spec/][%d] jobTemplatesJobTemplatesSurveySpecCreateBadRequest ", 400)
}

func (o *JobTemplatesJobTemplatesSurveySpecCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewJobTemplatesJobTemplatesSurveySpecCreateForbidden creates a JobTemplatesJobTemplatesSurveySpecCreateForbidden with default headers values
func NewJobTemplatesJobTemplatesSurveySpecCreateForbidden() *JobTemplatesJobTemplatesSurveySpecCreateForbidden {
	return &JobTemplatesJobTemplatesSurveySpecCreateForbidden{}
}

/*
JobTemplatesJobTemplatesSurveySpecCreateForbidden describes a response with status code 403, with default header values.

forbidden
*/
type JobTemplatesJobTemplatesSurveySpecCreateForbidden struct {
}

// IsSuccess returns true when this job templates job templates survey spec create forbidden response has a 2xx status code
func (o *JobTemplatesJobTemplatesSurveySpecCreateForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this job templates job templates survey spec create forbidden response has a 3xx status code
func (o *JobTemplatesJobTemplatesSurveySpecCreateForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this job templates job templates survey spec create forbidden response has a 4xx status code
func (o *JobTemplatesJobTemplatesSurveySpecCreateForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this job templates job templates survey spec create forbidden response has a 5xx status code
func (o *JobTemplatesJobTemplatesSurveySpecCreateForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this job templates job templates survey spec create forbidden response a status code equal to that given
func (o *JobTemplatesJobTemplatesSurveySpecCreateForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *JobTemplatesJobTemplatesSurveySpecCreateForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/job_templates/{id}/survey_spec/][%d] jobTemplatesJobTemplatesSurveySpecCreateForbidden ", 403)
}

func (o *JobTemplatesJobTemplatesSurveySpecCreateForbidden) String() string {
	return fmt.Sprintf("[POST /api/v2/job_templates/{id}/survey_spec/][%d] jobTemplatesJobTemplatesSurveySpecCreateForbidden ", 403)
}

func (o *JobTemplatesJobTemplatesSurveySpecCreateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
