// Code generated by go-swagger; DO NOT EDIT.

package job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// JobTemplatesJobTemplatesCreateReader is a Reader for the JobTemplatesJobTemplatesCreate structure.
type JobTemplatesJobTemplatesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobTemplatesJobTemplatesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewJobTemplatesJobTemplatesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewJobTemplatesJobTemplatesCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewJobTemplatesJobTemplatesCreateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewJobTemplatesJobTemplatesCreateCreated creates a JobTemplatesJobTemplatesCreateCreated with default headers values
func NewJobTemplatesJobTemplatesCreateCreated() *JobTemplatesJobTemplatesCreateCreated {
	return &JobTemplatesJobTemplatesCreateCreated{}
}

/*
JobTemplatesJobTemplatesCreateCreated describes a response with status code 201, with default header values.

JobTemplatesJobTemplatesCreateCreated job templates job templates create created
*/
type JobTemplatesJobTemplatesCreateCreated struct {
}

// IsSuccess returns true when this job templates job templates create created response has a 2xx status code
func (o *JobTemplatesJobTemplatesCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this job templates job templates create created response has a 3xx status code
func (o *JobTemplatesJobTemplatesCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this job templates job templates create created response has a 4xx status code
func (o *JobTemplatesJobTemplatesCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this job templates job templates create created response has a 5xx status code
func (o *JobTemplatesJobTemplatesCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this job templates job templates create created response a status code equal to that given
func (o *JobTemplatesJobTemplatesCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *JobTemplatesJobTemplatesCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/job_templates/][%d] jobTemplatesJobTemplatesCreateCreated ", 201)
}

func (o *JobTemplatesJobTemplatesCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/job_templates/][%d] jobTemplatesJobTemplatesCreateCreated ", 201)
}

func (o *JobTemplatesJobTemplatesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewJobTemplatesJobTemplatesCreateBadRequest creates a JobTemplatesJobTemplatesCreateBadRequest with default headers values
func NewJobTemplatesJobTemplatesCreateBadRequest() *JobTemplatesJobTemplatesCreateBadRequest {
	return &JobTemplatesJobTemplatesCreateBadRequest{}
}

/*
JobTemplatesJobTemplatesCreateBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type JobTemplatesJobTemplatesCreateBadRequest struct {
}

// IsSuccess returns true when this job templates job templates create bad request response has a 2xx status code
func (o *JobTemplatesJobTemplatesCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this job templates job templates create bad request response has a 3xx status code
func (o *JobTemplatesJobTemplatesCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this job templates job templates create bad request response has a 4xx status code
func (o *JobTemplatesJobTemplatesCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this job templates job templates create bad request response has a 5xx status code
func (o *JobTemplatesJobTemplatesCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this job templates job templates create bad request response a status code equal to that given
func (o *JobTemplatesJobTemplatesCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *JobTemplatesJobTemplatesCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/job_templates/][%d] jobTemplatesJobTemplatesCreateBadRequest ", 400)
}

func (o *JobTemplatesJobTemplatesCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v2/job_templates/][%d] jobTemplatesJobTemplatesCreateBadRequest ", 400)
}

func (o *JobTemplatesJobTemplatesCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewJobTemplatesJobTemplatesCreateForbidden creates a JobTemplatesJobTemplatesCreateForbidden with default headers values
func NewJobTemplatesJobTemplatesCreateForbidden() *JobTemplatesJobTemplatesCreateForbidden {
	return &JobTemplatesJobTemplatesCreateForbidden{}
}

/*
JobTemplatesJobTemplatesCreateForbidden describes a response with status code 403, with default header values.

forbidden
*/
type JobTemplatesJobTemplatesCreateForbidden struct {
}

// IsSuccess returns true when this job templates job templates create forbidden response has a 2xx status code
func (o *JobTemplatesJobTemplatesCreateForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this job templates job templates create forbidden response has a 3xx status code
func (o *JobTemplatesJobTemplatesCreateForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this job templates job templates create forbidden response has a 4xx status code
func (o *JobTemplatesJobTemplatesCreateForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this job templates job templates create forbidden response has a 5xx status code
func (o *JobTemplatesJobTemplatesCreateForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this job templates job templates create forbidden response a status code equal to that given
func (o *JobTemplatesJobTemplatesCreateForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *JobTemplatesJobTemplatesCreateForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/job_templates/][%d] jobTemplatesJobTemplatesCreateForbidden ", 403)
}

func (o *JobTemplatesJobTemplatesCreateForbidden) String() string {
	return fmt.Sprintf("[POST /api/v2/job_templates/][%d] jobTemplatesJobTemplatesCreateForbidden ", 403)
}

func (o *JobTemplatesJobTemplatesCreateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
