// Code generated by go-swagger; DO NOT EDIT.

package job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// JobTemplatesJobTemplatesAccessListListReader is a Reader for the JobTemplatesJobTemplatesAccessListList structure.
type JobTemplatesJobTemplatesAccessListListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobTemplatesJobTemplatesAccessListListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJobTemplatesJobTemplatesAccessListListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewJobTemplatesJobTemplatesAccessListListOK creates a JobTemplatesJobTemplatesAccessListListOK with default headers values
func NewJobTemplatesJobTemplatesAccessListListOK() *JobTemplatesJobTemplatesAccessListListOK {
	return &JobTemplatesJobTemplatesAccessListListOK{}
}

/*
JobTemplatesJobTemplatesAccessListListOK describes a response with status code 200, with default header values.

JobTemplatesJobTemplatesAccessListListOK job templates job templates access list list o k
*/
type JobTemplatesJobTemplatesAccessListListOK struct {
}

// IsSuccess returns true when this job templates job templates access list list o k response has a 2xx status code
func (o *JobTemplatesJobTemplatesAccessListListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this job templates job templates access list list o k response has a 3xx status code
func (o *JobTemplatesJobTemplatesAccessListListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this job templates job templates access list list o k response has a 4xx status code
func (o *JobTemplatesJobTemplatesAccessListListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this job templates job templates access list list o k response has a 5xx status code
func (o *JobTemplatesJobTemplatesAccessListListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this job templates job templates access list list o k response a status code equal to that given
func (o *JobTemplatesJobTemplatesAccessListListOK) IsCode(code int) bool {
	return code == 200
}

func (o *JobTemplatesJobTemplatesAccessListListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/job_templates/{id}/access_list/][%d] jobTemplatesJobTemplatesAccessListListOK ", 200)
}

func (o *JobTemplatesJobTemplatesAccessListListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/job_templates/{id}/access_list/][%d] jobTemplatesJobTemplatesAccessListListOK ", 200)
}

func (o *JobTemplatesJobTemplatesAccessListListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
