// Code generated by go-swagger; DO NOT EDIT.

package ad_hoc_commands

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AdHocCommandsAdHocCommandsCancelCreateReader is a Reader for the AdHocCommandsAdHocCommandsCancelCreate structure.
type AdHocCommandsAdHocCommandsCancelCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AdHocCommandsAdHocCommandsCancelCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAdHocCommandsAdHocCommandsCancelCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAdHocCommandsAdHocCommandsCancelCreateCreated creates a AdHocCommandsAdHocCommandsCancelCreateCreated with default headers values
func NewAdHocCommandsAdHocCommandsCancelCreateCreated() *AdHocCommandsAdHocCommandsCancelCreateCreated {
	return &AdHocCommandsAdHocCommandsCancelCreateCreated{}
}

/*
AdHocCommandsAdHocCommandsCancelCreateCreated describes a response with status code 201, with default header values.

AdHocCommandsAdHocCommandsCancelCreateCreated ad hoc commands ad hoc commands cancel create created
*/
type AdHocCommandsAdHocCommandsCancelCreateCreated struct {
}

// IsSuccess returns true when this ad hoc commands ad hoc commands cancel create created response has a 2xx status code
func (o *AdHocCommandsAdHocCommandsCancelCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ad hoc commands ad hoc commands cancel create created response has a 3xx status code
func (o *AdHocCommandsAdHocCommandsCancelCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ad hoc commands ad hoc commands cancel create created response has a 4xx status code
func (o *AdHocCommandsAdHocCommandsCancelCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this ad hoc commands ad hoc commands cancel create created response has a 5xx status code
func (o *AdHocCommandsAdHocCommandsCancelCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this ad hoc commands ad hoc commands cancel create created response a status code equal to that given
func (o *AdHocCommandsAdHocCommandsCancelCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *AdHocCommandsAdHocCommandsCancelCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/ad_hoc_commands/{id}/cancel/][%d] adHocCommandsAdHocCommandsCancelCreateCreated ", 201)
}

func (o *AdHocCommandsAdHocCommandsCancelCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/ad_hoc_commands/{id}/cancel/][%d] adHocCommandsAdHocCommandsCancelCreateCreated ", 201)
}

func (o *AdHocCommandsAdHocCommandsCancelCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
