// Code generated by go-swagger; DO NOT EDIT.

package instance_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// InstanceGroupsInstanceGroupsDeleteReader is a Reader for the InstanceGroupsInstanceGroupsDelete structure.
type InstanceGroupsInstanceGroupsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InstanceGroupsInstanceGroupsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewInstanceGroupsInstanceGroupsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewInstanceGroupsInstanceGroupsDeleteForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewInstanceGroupsInstanceGroupsDeleteConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewInstanceGroupsInstanceGroupsDeleteNoContent creates a InstanceGroupsInstanceGroupsDeleteNoContent with default headers values
func NewInstanceGroupsInstanceGroupsDeleteNoContent() *InstanceGroupsInstanceGroupsDeleteNoContent {
	return &InstanceGroupsInstanceGroupsDeleteNoContent{}
}

/*
InstanceGroupsInstanceGroupsDeleteNoContent describes a response with status code 204, with default header values.

InstanceGroupsInstanceGroupsDeleteNoContent instance groups instance groups delete no content
*/
type InstanceGroupsInstanceGroupsDeleteNoContent struct {
}

// IsSuccess returns true when this instance groups instance groups delete no content response has a 2xx status code
func (o *InstanceGroupsInstanceGroupsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this instance groups instance groups delete no content response has a 3xx status code
func (o *InstanceGroupsInstanceGroupsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance groups instance groups delete no content response has a 4xx status code
func (o *InstanceGroupsInstanceGroupsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this instance groups instance groups delete no content response has a 5xx status code
func (o *InstanceGroupsInstanceGroupsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this instance groups instance groups delete no content response a status code equal to that given
func (o *InstanceGroupsInstanceGroupsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *InstanceGroupsInstanceGroupsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/instance_groups/{id}/][%d] instanceGroupsInstanceGroupsDeleteNoContent ", 204)
}

func (o *InstanceGroupsInstanceGroupsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/v2/instance_groups/{id}/][%d] instanceGroupsInstanceGroupsDeleteNoContent ", 204)
}

func (o *InstanceGroupsInstanceGroupsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceGroupsInstanceGroupsDeleteForbidden creates a InstanceGroupsInstanceGroupsDeleteForbidden with default headers values
func NewInstanceGroupsInstanceGroupsDeleteForbidden() *InstanceGroupsInstanceGroupsDeleteForbidden {
	return &InstanceGroupsInstanceGroupsDeleteForbidden{}
}

/*
InstanceGroupsInstanceGroupsDeleteForbidden describes a response with status code 403, with default header values.

forbidden
*/
type InstanceGroupsInstanceGroupsDeleteForbidden struct {
}

// IsSuccess returns true when this instance groups instance groups delete forbidden response has a 2xx status code
func (o *InstanceGroupsInstanceGroupsDeleteForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance groups instance groups delete forbidden response has a 3xx status code
func (o *InstanceGroupsInstanceGroupsDeleteForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance groups instance groups delete forbidden response has a 4xx status code
func (o *InstanceGroupsInstanceGroupsDeleteForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance groups instance groups delete forbidden response has a 5xx status code
func (o *InstanceGroupsInstanceGroupsDeleteForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this instance groups instance groups delete forbidden response a status code equal to that given
func (o *InstanceGroupsInstanceGroupsDeleteForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *InstanceGroupsInstanceGroupsDeleteForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/instance_groups/{id}/][%d] instanceGroupsInstanceGroupsDeleteForbidden ", 403)
}

func (o *InstanceGroupsInstanceGroupsDeleteForbidden) String() string {
	return fmt.Sprintf("[DELETE /api/v2/instance_groups/{id}/][%d] instanceGroupsInstanceGroupsDeleteForbidden ", 403)
}

func (o *InstanceGroupsInstanceGroupsDeleteForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceGroupsInstanceGroupsDeleteConflict creates a InstanceGroupsInstanceGroupsDeleteConflict with default headers values
func NewInstanceGroupsInstanceGroupsDeleteConflict() *InstanceGroupsInstanceGroupsDeleteConflict {
	return &InstanceGroupsInstanceGroupsDeleteConflict{}
}

/*
InstanceGroupsInstanceGroupsDeleteConflict describes a response with status code 409, with default header values.

InstanceGroupsInstanceGroupsDeleteConflict instance groups instance groups delete conflict
*/
type InstanceGroupsInstanceGroupsDeleteConflict struct {
}

// IsSuccess returns true when this instance groups instance groups delete conflict response has a 2xx status code
func (o *InstanceGroupsInstanceGroupsDeleteConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance groups instance groups delete conflict response has a 3xx status code
func (o *InstanceGroupsInstanceGroupsDeleteConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance groups instance groups delete conflict response has a 4xx status code
func (o *InstanceGroupsInstanceGroupsDeleteConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance groups instance groups delete conflict response has a 5xx status code
func (o *InstanceGroupsInstanceGroupsDeleteConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this instance groups instance groups delete conflict response a status code equal to that given
func (o *InstanceGroupsInstanceGroupsDeleteConflict) IsCode(code int) bool {
	return code == 409
}

func (o *InstanceGroupsInstanceGroupsDeleteConflict) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/instance_groups/{id}/][%d] instanceGroupsInstanceGroupsDeleteConflict ", 409)
}

func (o *InstanceGroupsInstanceGroupsDeleteConflict) String() string {
	return fmt.Sprintf("[DELETE /api/v2/instance_groups/{id}/][%d] instanceGroupsInstanceGroupsDeleteConflict ", 409)
}

func (o *InstanceGroupsInstanceGroupsDeleteConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
