// Code generated by go-swagger; DO NOT EDIT.

package instance_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// InstanceGroupsInstanceGroupsJobsListReader is a Reader for the InstanceGroupsInstanceGroupsJobsList structure.
type InstanceGroupsInstanceGroupsJobsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InstanceGroupsInstanceGroupsJobsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInstanceGroupsInstanceGroupsJobsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewInstanceGroupsInstanceGroupsJobsListOK creates a InstanceGroupsInstanceGroupsJobsListOK with default headers values
func NewInstanceGroupsInstanceGroupsJobsListOK() *InstanceGroupsInstanceGroupsJobsListOK {
	return &InstanceGroupsInstanceGroupsJobsListOK{}
}

/*
InstanceGroupsInstanceGroupsJobsListOK describes a response with status code 200, with default header values.

InstanceGroupsInstanceGroupsJobsListOK instance groups instance groups jobs list o k
*/
type InstanceGroupsInstanceGroupsJobsListOK struct {
}

// IsSuccess returns true when this instance groups instance groups jobs list o k response has a 2xx status code
func (o *InstanceGroupsInstanceGroupsJobsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this instance groups instance groups jobs list o k response has a 3xx status code
func (o *InstanceGroupsInstanceGroupsJobsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance groups instance groups jobs list o k response has a 4xx status code
func (o *InstanceGroupsInstanceGroupsJobsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this instance groups instance groups jobs list o k response has a 5xx status code
func (o *InstanceGroupsInstanceGroupsJobsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this instance groups instance groups jobs list o k response a status code equal to that given
func (o *InstanceGroupsInstanceGroupsJobsListOK) IsCode(code int) bool {
	return code == 200
}

func (o *InstanceGroupsInstanceGroupsJobsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/instance_groups/{id}/jobs/][%d] instanceGroupsInstanceGroupsJobsListOK ", 200)
}

func (o *InstanceGroupsInstanceGroupsJobsListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/instance_groups/{id}/jobs/][%d] instanceGroupsInstanceGroupsJobsListOK ", 200)
}

func (o *InstanceGroupsInstanceGroupsJobsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
