// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AuthenticationApplicationsList0Reader is a Reader for the AuthenticationApplicationsList0 structure.
type AuthenticationApplicationsList0Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthenticationApplicationsList0Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAuthenticationApplicationsList0OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAuthenticationApplicationsList0OK creates a AuthenticationApplicationsList0OK with default headers values
func NewAuthenticationApplicationsList0OK() *AuthenticationApplicationsList0OK {
	return &AuthenticationApplicationsList0OK{}
}

/*
AuthenticationApplicationsList0OK describes a response with status code 200, with default header values.

AuthenticationApplicationsList0OK authentication applications list0 o k
*/
type AuthenticationApplicationsList0OK struct {
}

// IsSuccess returns true when this authentication applications list0 o k response has a 2xx status code
func (o *AuthenticationApplicationsList0OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this authentication applications list0 o k response has a 3xx status code
func (o *AuthenticationApplicationsList0OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this authentication applications list0 o k response has a 4xx status code
func (o *AuthenticationApplicationsList0OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this authentication applications list0 o k response has a 5xx status code
func (o *AuthenticationApplicationsList0OK) IsServerError() bool {
	return false
}

// IsCode returns true when this authentication applications list0 o k response a status code equal to that given
func (o *AuthenticationApplicationsList0OK) IsCode(code int) bool {
	return code == 200
}

func (o *AuthenticationApplicationsList0OK) Error() string {
	return fmt.Sprintf("[GET /api/v2/applications/][%d] authenticationApplicationsList0OK ", 200)
}

func (o *AuthenticationApplicationsList0OK) String() string {
	return fmt.Sprintf("[GET /api/v2/applications/][%d] authenticationApplicationsList0OK ", 200)
}

func (o *AuthenticationApplicationsList0OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
