// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UsersUsersProjectsListReader is a Reader for the UsersUsersProjectsList structure.
type UsersUsersProjectsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersUsersProjectsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUsersUsersProjectsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUsersUsersProjectsListOK creates a UsersUsersProjectsListOK with default headers values
func NewUsersUsersProjectsListOK() *UsersUsersProjectsListOK {
	return &UsersUsersProjectsListOK{}
}

/*
UsersUsersProjectsListOK describes a response with status code 200, with default header values.

UsersUsersProjectsListOK users users projects list o k
*/
type UsersUsersProjectsListOK struct {
}

// IsSuccess returns true when this users users projects list o k response has a 2xx status code
func (o *UsersUsersProjectsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this users users projects list o k response has a 3xx status code
func (o *UsersUsersProjectsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users users projects list o k response has a 4xx status code
func (o *UsersUsersProjectsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this users users projects list o k response has a 5xx status code
func (o *UsersUsersProjectsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this users users projects list o k response a status code equal to that given
func (o *UsersUsersProjectsListOK) IsCode(code int) bool {
	return code == 200
}

func (o *UsersUsersProjectsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/users/{id}/projects/][%d] usersUsersProjectsListOK ", 200)
}

func (o *UsersUsersProjectsListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/users/{id}/projects/][%d] usersUsersProjectsListOK ", 200)
}

func (o *UsersUsersProjectsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
