// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UsersUsersOrganizationsListReader is a Reader for the UsersUsersOrganizationsList structure.
type UsersUsersOrganizationsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersUsersOrganizationsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUsersUsersOrganizationsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUsersUsersOrganizationsListOK creates a UsersUsersOrganizationsListOK with default headers values
func NewUsersUsersOrganizationsListOK() *UsersUsersOrganizationsListOK {
	return &UsersUsersOrganizationsListOK{}
}

/*
UsersUsersOrganizationsListOK describes a response with status code 200, with default header values.

UsersUsersOrganizationsListOK users users organizations list o k
*/
type UsersUsersOrganizationsListOK struct {
}

// IsSuccess returns true when this users users organizations list o k response has a 2xx status code
func (o *UsersUsersOrganizationsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this users users organizations list o k response has a 3xx status code
func (o *UsersUsersOrganizationsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users users organizations list o k response has a 4xx status code
func (o *UsersUsersOrganizationsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this users users organizations list o k response has a 5xx status code
func (o *UsersUsersOrganizationsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this users users organizations list o k response a status code equal to that given
func (o *UsersUsersOrganizationsListOK) IsCode(code int) bool {
	return code == 200
}

func (o *UsersUsersOrganizationsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/users/{id}/organizations/][%d] usersUsersOrganizationsListOK ", 200)
}

func (o *UsersUsersOrganizationsListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/users/{id}/organizations/][%d] usersUsersOrganizationsListOK ", 200)
}

func (o *UsersUsersOrganizationsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
