// Code generated by go-swagger; DO NOT EDIT.

package job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewJobTemplatesJobTemplatesCreateParams creates a new JobTemplatesJobTemplatesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewJobTemplatesJobTemplatesCreateParams() *JobTemplatesJobTemplatesCreateParams {
	return &JobTemplatesJobTemplatesCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewJobTemplatesJobTemplatesCreateParamsWithTimeout creates a new JobTemplatesJobTemplatesCreateParams object
// with the ability to set a timeout on a request.
func NewJobTemplatesJobTemplatesCreateParamsWithTimeout(timeout time.Duration) *JobTemplatesJobTemplatesCreateParams {
	return &JobTemplatesJobTemplatesCreateParams{
		timeout: timeout,
	}
}

// NewJobTemplatesJobTemplatesCreateParamsWithContext creates a new JobTemplatesJobTemplatesCreateParams object
// with the ability to set a context for a request.
func NewJobTemplatesJobTemplatesCreateParamsWithContext(ctx context.Context) *JobTemplatesJobTemplatesCreateParams {
	return &JobTemplatesJobTemplatesCreateParams{
		Context: ctx,
	}
}

// NewJobTemplatesJobTemplatesCreateParamsWithHTTPClient creates a new JobTemplatesJobTemplatesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewJobTemplatesJobTemplatesCreateParamsWithHTTPClient(client *http.Client) *JobTemplatesJobTemplatesCreateParams {
	return &JobTemplatesJobTemplatesCreateParams{
		HTTPClient: client,
	}
}

/*
JobTemplatesJobTemplatesCreateParams contains all the parameters to send to the API endpoint

	for the job templates job templates create operation.

	Typically these are written to a http.Request.
*/
type JobTemplatesJobTemplatesCreateParams struct {

	// Data.
	Data interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the job templates job templates create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *JobTemplatesJobTemplatesCreateParams) WithDefaults() *JobTemplatesJobTemplatesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the job templates job templates create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *JobTemplatesJobTemplatesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the job templates job templates create params
func (o *JobTemplatesJobTemplatesCreateParams) WithTimeout(timeout time.Duration) *JobTemplatesJobTemplatesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the job templates job templates create params
func (o *JobTemplatesJobTemplatesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the job templates job templates create params
func (o *JobTemplatesJobTemplatesCreateParams) WithContext(ctx context.Context) *JobTemplatesJobTemplatesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the job templates job templates create params
func (o *JobTemplatesJobTemplatesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the job templates job templates create params
func (o *JobTemplatesJobTemplatesCreateParams) WithHTTPClient(client *http.Client) *JobTemplatesJobTemplatesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the job templates job templates create params
func (o *JobTemplatesJobTemplatesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the job templates job templates create params
func (o *JobTemplatesJobTemplatesCreateParams) WithData(data interface{}) *JobTemplatesJobTemplatesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the job templates job templates create params
func (o *JobTemplatesJobTemplatesCreateParams) SetData(data interface{}) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *JobTemplatesJobTemplatesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
