// Code generated by go-swagger; DO NOT EDIT.

package system_jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SystemJobsSystemJobsEventsListReader is a Reader for the SystemJobsSystemJobsEventsList structure.
type SystemJobsSystemJobsEventsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemJobsSystemJobsEventsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSystemJobsSystemJobsEventsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSystemJobsSystemJobsEventsListOK creates a SystemJobsSystemJobsEventsListOK with default headers values
func NewSystemJobsSystemJobsEventsListOK() *SystemJobsSystemJobsEventsListOK {
	return &SystemJobsSystemJobsEventsListOK{}
}

/*
SystemJobsSystemJobsEventsListOK describes a response with status code 200, with default header values.

SystemJobsSystemJobsEventsListOK system jobs system jobs events list o k
*/
type SystemJobsSystemJobsEventsListOK struct {
}

// IsSuccess returns true when this system jobs system jobs events list o k response has a 2xx status code
func (o *SystemJobsSystemJobsEventsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this system jobs system jobs events list o k response has a 3xx status code
func (o *SystemJobsSystemJobsEventsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system jobs system jobs events list o k response has a 4xx status code
func (o *SystemJobsSystemJobsEventsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this system jobs system jobs events list o k response has a 5xx status code
func (o *SystemJobsSystemJobsEventsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this system jobs system jobs events list o k response a status code equal to that given
func (o *SystemJobsSystemJobsEventsListOK) IsCode(code int) bool {
	return code == 200
}

func (o *SystemJobsSystemJobsEventsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/system_jobs/{id}/events/][%d] systemJobsSystemJobsEventsListOK ", 200)
}

func (o *SystemJobsSystemJobsEventsListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/system_jobs/{id}/events/][%d] systemJobsSystemJobsEventsListOK ", 200)
}

func (o *SystemJobsSystemJobsEventsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
