// Code generated by go-swagger; DO NOT EDIT.

package inventories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// InventoriesInventoriesInventorySourcesListReader is a Reader for the InventoriesInventoriesInventorySourcesList structure.
type InventoriesInventoriesInventorySourcesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InventoriesInventoriesInventorySourcesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInventoriesInventoriesInventorySourcesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewInventoriesInventoriesInventorySourcesListOK creates a InventoriesInventoriesInventorySourcesListOK with default headers values
func NewInventoriesInventoriesInventorySourcesListOK() *InventoriesInventoriesInventorySourcesListOK {
	return &InventoriesInventoriesInventorySourcesListOK{}
}

/*
InventoriesInventoriesInventorySourcesListOK describes a response with status code 200, with default header values.

InventoriesInventoriesInventorySourcesListOK inventories inventories inventory sources list o k
*/
type InventoriesInventoriesInventorySourcesListOK struct {
}

// IsSuccess returns true when this inventories inventories inventory sources list o k response has a 2xx status code
func (o *InventoriesInventoriesInventorySourcesListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this inventories inventories inventory sources list o k response has a 3xx status code
func (o *InventoriesInventoriesInventorySourcesListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this inventories inventories inventory sources list o k response has a 4xx status code
func (o *InventoriesInventoriesInventorySourcesListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this inventories inventories inventory sources list o k response has a 5xx status code
func (o *InventoriesInventoriesInventorySourcesListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this inventories inventories inventory sources list o k response a status code equal to that given
func (o *InventoriesInventoriesInventorySourcesListOK) IsCode(code int) bool {
	return code == 200
}

func (o *InventoriesInventoriesInventorySourcesListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/inventories/{id}/inventory_sources/][%d] inventoriesInventoriesInventorySourcesListOK ", 200)
}

func (o *InventoriesInventoriesInventorySourcesListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/inventories/{id}/inventory_sources/][%d] inventoriesInventoriesInventorySourcesListOK ", 200)
}

func (o *InventoriesInventoriesInventorySourcesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
