// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TeamsTeamsActivityStreamListReader is a Reader for the TeamsTeamsActivityStreamList structure.
type TeamsTeamsActivityStreamListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TeamsTeamsActivityStreamListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTeamsTeamsActivityStreamListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTeamsTeamsActivityStreamListOK creates a TeamsTeamsActivityStreamListOK with default headers values
func NewTeamsTeamsActivityStreamListOK() *TeamsTeamsActivityStreamListOK {
	return &TeamsTeamsActivityStreamListOK{}
}

/*
TeamsTeamsActivityStreamListOK describes a response with status code 200, with default header values.

TeamsTeamsActivityStreamListOK teams teams activity stream list o k
*/
type TeamsTeamsActivityStreamListOK struct {
}

// IsSuccess returns true when this teams teams activity stream list o k response has a 2xx status code
func (o *TeamsTeamsActivityStreamListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this teams teams activity stream list o k response has a 3xx status code
func (o *TeamsTeamsActivityStreamListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this teams teams activity stream list o k response has a 4xx status code
func (o *TeamsTeamsActivityStreamListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this teams teams activity stream list o k response has a 5xx status code
func (o *TeamsTeamsActivityStreamListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this teams teams activity stream list o k response a status code equal to that given
func (o *TeamsTeamsActivityStreamListOK) IsCode(code int) bool {
	return code == 200
}

func (o *TeamsTeamsActivityStreamListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/teams/{id}/activity_stream/][%d] teamsTeamsActivityStreamListOK ", 200)
}

func (o *TeamsTeamsActivityStreamListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/teams/{id}/activity_stream/][%d] teamsTeamsActivityStreamListOK ", 200)
}

func (o *TeamsTeamsActivityStreamListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
