// Code generated by go-swagger; DO NOT EDIT.

package execution_environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExecutionEnvironmentsExecutionEnvironmentsCopyListReader is a Reader for the ExecutionEnvironmentsExecutionEnvironmentsCopyList structure.
type ExecutionEnvironmentsExecutionEnvironmentsCopyListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExecutionEnvironmentsExecutionEnvironmentsCopyListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExecutionEnvironmentsExecutionEnvironmentsCopyListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExecutionEnvironmentsExecutionEnvironmentsCopyListOK creates a ExecutionEnvironmentsExecutionEnvironmentsCopyListOK with default headers values
func NewExecutionEnvironmentsExecutionEnvironmentsCopyListOK() *ExecutionEnvironmentsExecutionEnvironmentsCopyListOK {
	return &ExecutionEnvironmentsExecutionEnvironmentsCopyListOK{}
}

/*
ExecutionEnvironmentsExecutionEnvironmentsCopyListOK describes a response with status code 200, with default header values.

ExecutionEnvironmentsExecutionEnvironmentsCopyListOK execution environments execution environments copy list o k
*/
type ExecutionEnvironmentsExecutionEnvironmentsCopyListOK struct {
}

// IsSuccess returns true when this execution environments execution environments copy list o k response has a 2xx status code
func (o *ExecutionEnvironmentsExecutionEnvironmentsCopyListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this execution environments execution environments copy list o k response has a 3xx status code
func (o *ExecutionEnvironmentsExecutionEnvironmentsCopyListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this execution environments execution environments copy list o k response has a 4xx status code
func (o *ExecutionEnvironmentsExecutionEnvironmentsCopyListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this execution environments execution environments copy list o k response has a 5xx status code
func (o *ExecutionEnvironmentsExecutionEnvironmentsCopyListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this execution environments execution environments copy list o k response a status code equal to that given
func (o *ExecutionEnvironmentsExecutionEnvironmentsCopyListOK) IsCode(code int) bool {
	return code == 200
}

func (o *ExecutionEnvironmentsExecutionEnvironmentsCopyListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/execution_environments/{id}/copy/][%d] executionEnvironmentsExecutionEnvironmentsCopyListOK ", 200)
}

func (o *ExecutionEnvironmentsExecutionEnvironmentsCopyListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/execution_environments/{id}/copy/][%d] executionEnvironmentsExecutionEnvironmentsCopyListOK ", 200)
}

func (o *ExecutionEnvironmentsExecutionEnvironmentsCopyListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
