// Code generated by go-swagger; DO NOT EDIT.

package execution_environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExecutionEnvironmentsExecutionEnvironmentsCreateReader is a Reader for the ExecutionEnvironmentsExecutionEnvironmentsCreate structure.
type ExecutionEnvironmentsExecutionEnvironmentsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewExecutionEnvironmentsExecutionEnvironmentsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExecutionEnvironmentsExecutionEnvironmentsCreateCreated creates a ExecutionEnvironmentsExecutionEnvironmentsCreateCreated with default headers values
func NewExecutionEnvironmentsExecutionEnvironmentsCreateCreated() *ExecutionEnvironmentsExecutionEnvironmentsCreateCreated {
	return &ExecutionEnvironmentsExecutionEnvironmentsCreateCreated{}
}

/*
ExecutionEnvironmentsExecutionEnvironmentsCreateCreated describes a response with status code 201, with default header values.

ExecutionEnvironmentsExecutionEnvironmentsCreateCreated execution environments execution environments create created
*/
type ExecutionEnvironmentsExecutionEnvironmentsCreateCreated struct {
}

// IsSuccess returns true when this execution environments execution environments create created response has a 2xx status code
func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this execution environments execution environments create created response has a 3xx status code
func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this execution environments execution environments create created response has a 4xx status code
func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this execution environments execution environments create created response has a 5xx status code
func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this execution environments execution environments create created response a status code equal to that given
func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/execution_environments/][%d] executionEnvironmentsExecutionEnvironmentsCreateCreated ", 201)
}

func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/execution_environments/][%d] executionEnvironmentsExecutionEnvironmentsCreateCreated ", 201)
}

func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
ExecutionEnvironmentsExecutionEnvironmentsCreateBody execution environments execution environments create body
swagger:model ExecutionEnvironmentsExecutionEnvironmentsCreateBody
*/
type ExecutionEnvironmentsExecutionEnvironmentsCreateBody struct {

	// credential
	Credential int64 `json:"credential,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// The full image location, including the container registry, image name, and version tag.
	// Required: true
	Image *string `json:"image"`

	// name
	// Required: true
	Name *string `json:"name"`

	// The organization used to determine access to this execution environment.
	Organization int64 `json:"organization,omitempty"`

	// Pull image before running?
	Pull string `json:"pull,omitempty"`
}

// Validate validates this execution environments execution environments create body
func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateImage(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateBody) validateImage(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"image", "body", o.Image); err != nil {
		return err
	}

	return nil
}

func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this execution environments execution environments create body based on context it is used
func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ExecutionEnvironmentsExecutionEnvironmentsCreateBody) UnmarshalBinary(b []byte) error {
	var res ExecutionEnvironmentsExecutionEnvironmentsCreateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
