// Code generated by go-swagger; DO NOT EDIT.

package execution_environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExecutionEnvironmentsExecutionEnvironmentsDeleteParams creates a new ExecutionEnvironmentsExecutionEnvironmentsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExecutionEnvironmentsExecutionEnvironmentsDeleteParams() *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams {
	return &ExecutionEnvironmentsExecutionEnvironmentsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExecutionEnvironmentsExecutionEnvironmentsDeleteParamsWithTimeout creates a new ExecutionEnvironmentsExecutionEnvironmentsDeleteParams object
// with the ability to set a timeout on a request.
func NewExecutionEnvironmentsExecutionEnvironmentsDeleteParamsWithTimeout(timeout time.Duration) *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams {
	return &ExecutionEnvironmentsExecutionEnvironmentsDeleteParams{
		timeout: timeout,
	}
}

// NewExecutionEnvironmentsExecutionEnvironmentsDeleteParamsWithContext creates a new ExecutionEnvironmentsExecutionEnvironmentsDeleteParams object
// with the ability to set a context for a request.
func NewExecutionEnvironmentsExecutionEnvironmentsDeleteParamsWithContext(ctx context.Context) *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams {
	return &ExecutionEnvironmentsExecutionEnvironmentsDeleteParams{
		Context: ctx,
	}
}

// NewExecutionEnvironmentsExecutionEnvironmentsDeleteParamsWithHTTPClient creates a new ExecutionEnvironmentsExecutionEnvironmentsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewExecutionEnvironmentsExecutionEnvironmentsDeleteParamsWithHTTPClient(client *http.Client) *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams {
	return &ExecutionEnvironmentsExecutionEnvironmentsDeleteParams{
		HTTPClient: client,
	}
}

/*
ExecutionEnvironmentsExecutionEnvironmentsDeleteParams contains all the parameters to send to the API endpoint

	for the execution environments execution environments delete operation.

	Typically these are written to a http.Request.
*/
type ExecutionEnvironmentsExecutionEnvironmentsDeleteParams struct {

	// ID.
	ID string

	/* Search.

	   A search term.
	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the execution environments execution environments delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams) WithDefaults() *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the execution environments execution environments delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the execution environments execution environments delete params
func (o *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams) WithTimeout(timeout time.Duration) *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the execution environments execution environments delete params
func (o *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the execution environments execution environments delete params
func (o *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams) WithContext(ctx context.Context) *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the execution environments execution environments delete params
func (o *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the execution environments execution environments delete params
func (o *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams) WithHTTPClient(client *http.Client) *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the execution environments execution environments delete params
func (o *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the execution environments execution environments delete params
func (o *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams) WithID(id string) *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the execution environments execution environments delete params
func (o *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams) SetID(id string) {
	o.ID = id
}

// WithSearch adds the search to the execution environments execution environments delete params
func (o *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams) WithSearch(search *string) *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the execution environments execution environments delete params
func (o *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *ExecutionEnvironmentsExecutionEnvironmentsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
