// Code generated by go-swagger; DO NOT EDIT.

package inventories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// InventoriesInventoriesInstanceGroupsCreateReader is a Reader for the InventoriesInventoriesInstanceGroupsCreate structure.
type InventoriesInventoriesInstanceGroupsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InventoriesInventoriesInstanceGroupsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewInventoriesInventoriesInstanceGroupsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewInventoriesInventoriesInstanceGroupsCreateCreated creates a InventoriesInventoriesInstanceGroupsCreateCreated with default headers values
func NewInventoriesInventoriesInstanceGroupsCreateCreated() *InventoriesInventoriesInstanceGroupsCreateCreated {
	return &InventoriesInventoriesInstanceGroupsCreateCreated{}
}

/*
InventoriesInventoriesInstanceGroupsCreateCreated describes a response with status code 201, with default header values.

InventoriesInventoriesInstanceGroupsCreateCreated inventories inventories instance groups create created
*/
type InventoriesInventoriesInstanceGroupsCreateCreated struct {
}

// IsSuccess returns true when this inventories inventories instance groups create created response has a 2xx status code
func (o *InventoriesInventoriesInstanceGroupsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this inventories inventories instance groups create created response has a 3xx status code
func (o *InventoriesInventoriesInstanceGroupsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this inventories inventories instance groups create created response has a 4xx status code
func (o *InventoriesInventoriesInstanceGroupsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this inventories inventories instance groups create created response has a 5xx status code
func (o *InventoriesInventoriesInstanceGroupsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this inventories inventories instance groups create created response a status code equal to that given
func (o *InventoriesInventoriesInstanceGroupsCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *InventoriesInventoriesInstanceGroupsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/inventories/{id}/instance_groups/][%d] inventoriesInventoriesInstanceGroupsCreateCreated ", 201)
}

func (o *InventoriesInventoriesInstanceGroupsCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/inventories/{id}/instance_groups/][%d] inventoriesInventoriesInstanceGroupsCreateCreated ", 201)
}

func (o *InventoriesInventoriesInstanceGroupsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
