// Code generated by go-swagger; DO NOT EDIT.

package workflow_job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListReader is a Reader for the WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessList structure.
type WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK creates a WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK with default headers values
func NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK() *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK {
	return &WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK{}
}

/*
WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK describes a response with status code 200, with default header values.

WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK workflow job templates workflow job templates notification templates success list o k
*/
type WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK struct {
}

// IsSuccess returns true when this workflow job templates workflow job templates notification templates success list o k response has a 2xx status code
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this workflow job templates workflow job templates notification templates success list o k response has a 3xx status code
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this workflow job templates workflow job templates notification templates success list o k response has a 4xx status code
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this workflow job templates workflow job templates notification templates success list o k response has a 5xx status code
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this workflow job templates workflow job templates notification templates success list o k response a status code equal to that given
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK) IsCode(code int) bool {
	return code == 200
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/workflow_job_templates/{id}/notification_templates_success/][%d] workflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK ", 200)
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/workflow_job_templates/{id}/notification_templates_success/][%d] workflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK ", 200)
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesSuccessListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
