// Code generated by go-swagger; DO NOT EDIT.

package workflow_job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateReader is a Reader for the WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreate structure.
type WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewWorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewWorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated creates a WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated with default headers values
func NewWorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated() *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated {
	return &WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated{}
}

/*
WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated describes a response with status code 201, with default header values.

WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated workflow job templates workflow job templates schedules create created
*/
type WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated struct {
}

// IsSuccess returns true when this workflow job templates workflow job templates schedules create created response has a 2xx status code
func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this workflow job templates workflow job templates schedules create created response has a 3xx status code
func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this workflow job templates workflow job templates schedules create created response has a 4xx status code
func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this workflow job templates workflow job templates schedules create created response has a 5xx status code
func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this workflow job templates workflow job templates schedules create created response a status code equal to that given
func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/workflow_job_templates/{id}/schedules/][%d] workflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated ", 201)
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated) String() string {
	return fmt.Sprintf("[POST /api/v2/workflow_job_templates/{id}/schedules/][%d] workflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated ", 201)
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewWorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest creates a WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest with default headers values
func NewWorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest() *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest {
	return &WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest{}
}

/*
WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest struct {
}

// IsSuccess returns true when this workflow job templates workflow job templates schedules create bad request response has a 2xx status code
func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this workflow job templates workflow job templates schedules create bad request response has a 3xx status code
func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this workflow job templates workflow job templates schedules create bad request response has a 4xx status code
func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this workflow job templates workflow job templates schedules create bad request response has a 5xx status code
func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this workflow job templates workflow job templates schedules create bad request response a status code equal to that given
func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/workflow_job_templates/{id}/schedules/][%d] workflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest ", 400)
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v2/workflow_job_templates/{id}/schedules/][%d] workflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest ", 400)
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
