// Code generated by go-swagger; DO NOT EDIT.

package settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SettingsSettingsDeleteReader is a Reader for the SettingsSettingsDelete structure.
type SettingsSettingsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SettingsSettingsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewSettingsSettingsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSettingsSettingsDeleteNoContent creates a SettingsSettingsDeleteNoContent with default headers values
func NewSettingsSettingsDeleteNoContent() *SettingsSettingsDeleteNoContent {
	return &SettingsSettingsDeleteNoContent{}
}

/*
SettingsSettingsDeleteNoContent describes a response with status code 204, with default header values.

SettingsSettingsDeleteNoContent settings settings delete no content
*/
type SettingsSettingsDeleteNoContent struct {
}

// IsSuccess returns true when this settings settings delete no content response has a 2xx status code
func (o *SettingsSettingsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this settings settings delete no content response has a 3xx status code
func (o *SettingsSettingsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this settings settings delete no content response has a 4xx status code
func (o *SettingsSettingsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this settings settings delete no content response has a 5xx status code
func (o *SettingsSettingsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this settings settings delete no content response a status code equal to that given
func (o *SettingsSettingsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *SettingsSettingsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/settings/{category_slug}/][%d] settingsSettingsDeleteNoContent ", 204)
}

func (o *SettingsSettingsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/v2/settings/{category_slug}/][%d] settingsSettingsDeleteNoContent ", 204)
}

func (o *SettingsSettingsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
