// Code generated by go-swagger; DO NOT EDIT.

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// JobsJobsCreateScheduleReadReader is a Reader for the JobsJobsCreateScheduleRead structure.
type JobsJobsCreateScheduleReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobsJobsCreateScheduleReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJobsJobsCreateScheduleReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewJobsJobsCreateScheduleReadOK creates a JobsJobsCreateScheduleReadOK with default headers values
func NewJobsJobsCreateScheduleReadOK() *JobsJobsCreateScheduleReadOK {
	return &JobsJobsCreateScheduleReadOK{}
}

/*
JobsJobsCreateScheduleReadOK describes a response with status code 200, with default header values.

JobsJobsCreateScheduleReadOK jobs jobs create schedule read o k
*/
type JobsJobsCreateScheduleReadOK struct {
}

// IsSuccess returns true when this jobs jobs create schedule read o k response has a 2xx status code
func (o *JobsJobsCreateScheduleReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this jobs jobs create schedule read o k response has a 3xx status code
func (o *JobsJobsCreateScheduleReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this jobs jobs create schedule read o k response has a 4xx status code
func (o *JobsJobsCreateScheduleReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this jobs jobs create schedule read o k response has a 5xx status code
func (o *JobsJobsCreateScheduleReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this jobs jobs create schedule read o k response a status code equal to that given
func (o *JobsJobsCreateScheduleReadOK) IsCode(code int) bool {
	return code == 200
}

func (o *JobsJobsCreateScheduleReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/jobs/{id}/create_schedule/][%d] jobsJobsCreateScheduleReadOK ", 200)
}

func (o *JobsJobsCreateScheduleReadOK) String() string {
	return fmt.Sprintf("[GET /api/v2/jobs/{id}/create_schedule/][%d] jobsJobsCreateScheduleReadOK ", 200)
}

func (o *JobsJobsCreateScheduleReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
