// Code generated by go-swagger; DO NOT EDIT.

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// JobsJobsCancelReadReader is a Reader for the JobsJobsCancelRead structure.
type JobsJobsCancelReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobsJobsCancelReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJobsJobsCancelReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewJobsJobsCancelReadOK creates a JobsJobsCancelReadOK with default headers values
func NewJobsJobsCancelReadOK() *JobsJobsCancelReadOK {
	return &JobsJobsCancelReadOK{}
}

/*
JobsJobsCancelReadOK describes a response with status code 200, with default header values.

JobsJobsCancelReadOK jobs jobs cancel read o k
*/
type JobsJobsCancelReadOK struct {
}

// IsSuccess returns true when this jobs jobs cancel read o k response has a 2xx status code
func (o *JobsJobsCancelReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this jobs jobs cancel read o k response has a 3xx status code
func (o *JobsJobsCancelReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this jobs jobs cancel read o k response has a 4xx status code
func (o *JobsJobsCancelReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this jobs jobs cancel read o k response has a 5xx status code
func (o *JobsJobsCancelReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this jobs jobs cancel read o k response a status code equal to that given
func (o *JobsJobsCancelReadOK) IsCode(code int) bool {
	return code == 200
}

func (o *JobsJobsCancelReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/jobs/{id}/cancel/][%d] jobsJobsCancelReadOK ", 200)
}

func (o *JobsJobsCancelReadOK) String() string {
	return fmt.Sprintf("[GET /api/v2/jobs/{id}/cancel/][%d] jobsJobsCancelReadOK ", 200)
}

func (o *JobsJobsCancelReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
