// Code generated by go-swagger; DO NOT EDIT.

package credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new credentials API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for credentials API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CredentialsCredentialsAccessListList(params *CredentialsCredentialsAccessListListParams, opts ...ClientOption) (*CredentialsCredentialsAccessListListOK, error)

	CredentialsCredentialsActivityStreamList(params *CredentialsCredentialsActivityStreamListParams, opts ...ClientOption) (*CredentialsCredentialsActivityStreamListOK, error)

	CredentialsCredentialsCopyCreate(params *CredentialsCredentialsCopyCreateParams, opts ...ClientOption) (*CredentialsCredentialsCopyCreateCreated, error)

	CredentialsCredentialsCopyList(params *CredentialsCredentialsCopyListParams, opts ...ClientOption) (*CredentialsCredentialsCopyListOK, error)

	CredentialsCredentialsCreate(params *CredentialsCredentialsCreateParams, opts ...ClientOption) (*CredentialsCredentialsCreateCreated, error)

	CredentialsCredentialsDelete(params *CredentialsCredentialsDeleteParams, opts ...ClientOption) (*CredentialsCredentialsDeleteNoContent, error)

	CredentialsCredentialsInputSourcesCreate(params *CredentialsCredentialsInputSourcesCreateParams, opts ...ClientOption) (*CredentialsCredentialsInputSourcesCreateCreated, error)

	CredentialsCredentialsInputSourcesList(params *CredentialsCredentialsInputSourcesListParams, opts ...ClientOption) (*CredentialsCredentialsInputSourcesListOK, error)

	CredentialsCredentialsList(params *CredentialsCredentialsListParams, opts ...ClientOption) (*CredentialsCredentialsListOK, error)

	CredentialsCredentialsObjectRolesList(params *CredentialsCredentialsObjectRolesListParams, opts ...ClientOption) (*CredentialsCredentialsObjectRolesListOK, error)

	CredentialsCredentialsOwnerTeamsList(params *CredentialsCredentialsOwnerTeamsListParams, opts ...ClientOption) (*CredentialsCredentialsOwnerTeamsListOK, error)

	CredentialsCredentialsOwnerUsersList(params *CredentialsCredentialsOwnerUsersListParams, opts ...ClientOption) (*CredentialsCredentialsOwnerUsersListOK, error)

	CredentialsCredentialsPartialUpdate(params *CredentialsCredentialsPartialUpdateParams, opts ...ClientOption) (*CredentialsCredentialsPartialUpdateOK, error)

	CredentialsCredentialsRead(params *CredentialsCredentialsReadParams, opts ...ClientOption) (*CredentialsCredentialsReadOK, error)

	CredentialsCredentialsTestCreate(params *CredentialsCredentialsTestCreateParams, opts ...ClientOption) (*CredentialsCredentialsTestCreateCreated, *CredentialsCredentialsTestCreateAccepted, error)

	CredentialsCredentialsTestRead(params *CredentialsCredentialsTestReadParams, opts ...ClientOption) (*CredentialsCredentialsTestReadOK, error)

	CredentialsCredentialsUpdate(params *CredentialsCredentialsUpdateParams, opts ...ClientOption) (*CredentialsCredentialsUpdateOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
	CredentialsCredentialsAccessListList lists users

Make a GET request to this resource to retrieve the list of
users.

The resulting data structure contains:

	{
	    "count": 99,
	    "next": null,
	    "previous": null,
	    "results": [
	        ...
	    ]
	}

The `count` field indicates the total number of users
found for the given query.  The `next` and `previous` fields provides links to
additional results if there are more than will fit on a single page.  The
`results` list contains zero or more user records.

## Results

Each user data structure includes the following fields:

* `id`: Database ID for this user. (integer)
* `type`: Data type for this user. (choice)
* `url`: URL for this user. (string)
* `related`: Data structure with URLs of related resources. (object)
* `summary_fields`: Data structure with name/description for related resources.  The output for some objects may be limited for performance reasons. (object)
* `created`: Timestamp when this user was created. (datetime)
* `modified`: Timestamp when this user was last modified. (datetime)
* `username`: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. (string)
* `first_name`:  (string)
* `last_name`:  (string)
* `email`:  (string)
* `is_superuser`: Designates that this user has all permissions without explicitly assigning them. (boolean)
* `is_system_auditor`:  (boolean)

* `ldap_dn`:  (string)
* `last_login`:  (datetime)
* `external_account`: Set if the account is managed by an external service (field)

## Sorting

To specify that users are returned in a particular
order, use the `order_by` query string parameter on the GET request.

	?order_by=username

Prefix the field name with a dash `-` to sort in reverse:

	?order_by=-username

Multiple sorting fields may be specified by separating the field names with a
comma `,`:

	?order_by=username,some_other_field

## Pagination

Use the `page_size` query string parameter to change the number of results
returned for each request.  Use the `page` query string parameter to retrieve
a particular page of results.

	?page_size=100&page=2

The `previous` and `next` links returned with the results will set these query
string parameters automatically.

## Searching

Use the `search` query string parameter to perform a case-insensitive search
within all designated text fields of a model.

	?search=findme

(_Added in Ansible Tower 3.1.0_) Search across related fields:

	?related__search=findme
*/
func (a *Client) CredentialsCredentialsAccessListList(params *CredentialsCredentialsAccessListListParams, opts ...ClientOption) (*CredentialsCredentialsAccessListListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsAccessListListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_access_list_list",
		Method:             "GET",
		PathPattern:        "/api/v2/credentials/{id}/access_list/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsAccessListListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsAccessListListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_access_list_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsActivityStreamList lists activity streams for a credential

Make a GET request to this resource to retrieve a list of
activity streams associated with the selected
credential.

The resulting data structure contains:

	{
	    "count": 99,
	    "next": null,
	    "previous": null,
	    "results": [
	        ...
	    ]
	}

The `count` field indicates the total number of activity streams
found for the given query.  The `next` and `previous` fields provides links to
additional results if there are more than will fit on a single page.  The
`results` list contains zero or more activity stream records.

## Results

Each activity stream data structure includes the following fields:

* `id`: Database ID for this activity stream. (integer)
* `type`: Data type for this activity stream. (choice)
* `url`: URL for this activity stream. (string)
* `related`: Data structure with URLs of related resources. (object)
* `summary_fields`: Data structure with name/description for related resources.  The output for some objects may be limited for performance reasons. (object)
* `timestamp`:  (datetime)
* `operation`: The action taken with respect to the given object(s). (choice)
  - `create`: Entity Created
  - `update`: Entity Updated
  - `delete`: Entity Deleted
  - `associate`: Entity Associated with another Entity
  - `disassociate`: Entity was Disassociated with another Entity

* `changes`: A summary of the new and changed values when an object is created, updated, or deleted (json)
* `object1`: For create, update, and delete events this is the object type that was affected. For associate and disassociate events this is the object type associated or disassociated with object2. (string)
* `object2`: Unpopulated for create, update, and delete events. For associate and disassociate events this is the object type that object1 is being associated with. (string)
* `object_association`: When present, shows the field name of the role or relationship that changed. (field)
* `action_node`: The cluster node the activity took place on. (string)
* `object_type`: When present, shows the model on which the role or relationship was defined. (field)

## Sorting

To specify that activity streams are returned in a particular
order, use the `order_by` query string parameter on the GET request.

	?order_by=name

Prefix the field name with a dash `-` to sort in reverse:

	?order_by=-name

Multiple sorting fields may be specified by separating the field names with a
comma `,`:

	?order_by=name,some_other_field

## Pagination

Use the `page_size` query string parameter to change the number of results
returned for each request.  Use the `page` query string parameter to retrieve
a particular page of results.

	?page_size=100&page=2

The `previous` and `next` links returned with the results will set these query
string parameters automatically.

## Searching

Use the `search` query string parameter to perform a case-insensitive search
within all designated text fields of a model.

	?search=findme

(_Added in Ansible Tower 3.1.0_) Search across related fields:

	?related__search=findme
*/
func (a *Client) CredentialsCredentialsActivityStreamList(params *CredentialsCredentialsActivityStreamListParams, opts ...ClientOption) (*CredentialsCredentialsActivityStreamListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsActivityStreamListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_activity_stream_list",
		Method:             "GET",
		PathPattern:        "/api/v2/credentials/{id}/activity_stream/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsActivityStreamListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsActivityStreamListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_activity_stream_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
CredentialsCredentialsCopyCreate credentials credentials copy create API
*/
func (a *Client) CredentialsCredentialsCopyCreate(params *CredentialsCredentialsCopyCreateParams, opts ...ClientOption) (*CredentialsCredentialsCopyCreateCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsCopyCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_copy_create",
		Method:             "POST",
		PathPattern:        "/api/v2/credentials/{id}/copy/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsCopyCreateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsCopyCreateCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_copy_create: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
CredentialsCredentialsCopyList credentials credentials copy list API
*/
func (a *Client) CredentialsCredentialsCopyList(params *CredentialsCredentialsCopyListParams, opts ...ClientOption) (*CredentialsCredentialsCopyListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsCopyListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_copy_list",
		Method:             "GET",
		PathPattern:        "/api/v2/credentials/{id}/copy/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsCopyListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsCopyListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_copy_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsCreate creates a credential

Make a POST request to this resource with the following credential
fields to create a new credential:

* `name`: Name of this credential. (string, required)
* `description`: Optional description of this credential. (string, default=`""`)
* `organization`: Inherit permissions from organization roles. If provided on creation, do not give either user or team. (id, default=`None`)
* `credential_type`: Specify the type of credential you want to create. Refer to the documentation for details on each type. (id, required)

* `inputs`: Enter inputs using either JSON or YAML syntax. Refer to the documentation for example syntax. (json, default=`{}`)

* `user`: Write-only field used to add user to owner role. If provided, do not give either team or organization. Only valid for creation. (id, default=`None`)
* `team`: Write-only field used to add team to owner role. If provided, do not give either user or organization. Only valid for creation. (id, default=`None`)
*/
func (a *Client) CredentialsCredentialsCreate(params *CredentialsCredentialsCreateParams, opts ...ClientOption) (*CredentialsCredentialsCreateCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_create",
		Method:             "POST",
		PathPattern:        "/api/v2/credentials/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsCreateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsCreateCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_create: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsDelete deletes a credential

Make a DELETE request to this resource to delete this credential.
*/
func (a *Client) CredentialsCredentialsDelete(params *CredentialsCredentialsDeleteParams, opts ...ClientOption) (*CredentialsCredentialsDeleteNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsDeleteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_delete",
		Method:             "DELETE",
		PathPattern:        "/api/v2/credentials/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsDeleteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsDeleteNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_delete: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsInputSourcesCreate creates a credential input source for a credential

Make a POST request to this resource with the following credential input source
fields to create a new credential input source associated with this
credential.

* `description`: Optional description of this credential input source. (string, default=`""`)
* `input_field_name`:  (string, required)
* `metadata`:  (json, default=`{}`)

* `source_credential`:  (id, required)
*/
func (a *Client) CredentialsCredentialsInputSourcesCreate(params *CredentialsCredentialsInputSourcesCreateParams, opts ...ClientOption) (*CredentialsCredentialsInputSourcesCreateCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsInputSourcesCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_input_sources_create",
		Method:             "POST",
		PathPattern:        "/api/v2/credentials/{id}/input_sources/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsInputSourcesCreateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsInputSourcesCreateCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_input_sources_create: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsInputSourcesList lists credential input sources for a credential

Make a GET request to this resource to retrieve a list of
credential input sources associated with the selected
credential.

The resulting data structure contains:

	{
	    "count": 99,
	    "next": null,
	    "previous": null,
	    "results": [
	        ...
	    ]
	}

The `count` field indicates the total number of credential input sources
found for the given query.  The `next` and `previous` fields provides links to
additional results if there are more than will fit on a single page.  The
`results` list contains zero or more credential input source records.

## Results

Each credential input source data structure includes the following fields:

* `id`: Database ID for this credential input source. (integer)
* `type`: Data type for this credential input source. (choice)
* `url`: URL for this credential input source. (string)
* `related`: Data structure with URLs of related resources. (object)
* `summary_fields`: Data structure with name/description for related resources.  The output for some objects may be limited for performance reasons. (object)
* `created`: Timestamp when this credential input source was created. (datetime)
* `modified`: Timestamp when this credential input source was last modified. (datetime)
* `description`: Optional description of this credential input source. (string)
* `input_field_name`:  (string)
* `metadata`:  (json)
* `target_credential`:  (id)
* `source_credential`:  (id)

## Sorting

To specify that credential input sources are returned in a particular
order, use the `order_by` query string parameter on the GET request.

	?order_by=name

Prefix the field name with a dash `-` to sort in reverse:

	?order_by=-name

Multiple sorting fields may be specified by separating the field names with a
comma `,`:

	?order_by=name,some_other_field

## Pagination

Use the `page_size` query string parameter to change the number of results
returned for each request.  Use the `page` query string parameter to retrieve
a particular page of results.

	?page_size=100&page=2

The `previous` and `next` links returned with the results will set these query
string parameters automatically.

## Searching

Use the `search` query string parameter to perform a case-insensitive search
within all designated text fields of a model.

	?search=findme

(_Added in Ansible Tower 3.1.0_) Search across related fields:

	?related__search=findme
*/
func (a *Client) CredentialsCredentialsInputSourcesList(params *CredentialsCredentialsInputSourcesListParams, opts ...ClientOption) (*CredentialsCredentialsInputSourcesListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsInputSourcesListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_input_sources_list",
		Method:             "GET",
		PathPattern:        "/api/v2/credentials/{id}/input_sources/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsInputSourcesListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsInputSourcesListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_input_sources_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsList lists credentials

Make a GET request to this resource to retrieve the list of
credentials.

The resulting data structure contains:

	{
	    "count": 99,
	    "next": null,
	    "previous": null,
	    "results": [
	        ...
	    ]
	}

The `count` field indicates the total number of credentials
found for the given query.  The `next` and `previous` fields provides links to
additional results if there are more than will fit on a single page.  The
`results` list contains zero or more credential records.

## Results

Each credential data structure includes the following fields:

* `id`: Database ID for this credential. (integer)
* `type`: Data type for this credential. (choice)
* `url`: URL for this credential. (string)
* `related`: Data structure with URLs of related resources. (object)
* `summary_fields`: Data structure with name/description for related resources.  The output for some objects may be limited for performance reasons. (object)
* `created`: Timestamp when this credential was created. (datetime)
* `modified`: Timestamp when this credential was last modified. (datetime)
* `name`: Name of this credential. (string)
* `description`: Optional description of this credential. (string)
* `organization`: Inherit permissions from organization roles. If provided on creation, do not give either user or team. (id)
* `credential_type`: Specify the type of credential you want to create. Refer to the documentation for details on each type. (id)
* `managed`:  (boolean)
* `inputs`: Enter inputs using either JSON or YAML syntax. Refer to the documentation for example syntax. (json)
* `kind`:  (field)
* `cloud`:  (field)
* `kubernetes`:  (field)

## Sorting

To specify that credentials are returned in a particular
order, use the `order_by` query string parameter on the GET request.

	?order_by=name

Prefix the field name with a dash `-` to sort in reverse:

	?order_by=-name

Multiple sorting fields may be specified by separating the field names with a
comma `,`:

	?order_by=name,some_other_field

## Pagination

Use the `page_size` query string parameter to change the number of results
returned for each request.  Use the `page` query string parameter to retrieve
a particular page of results.

	?page_size=100&page=2

The `previous` and `next` links returned with the results will set these query
string parameters automatically.

## Searching

Use the `search` query string parameter to perform a case-insensitive search
within all designated text fields of a model.

	?search=findme

(_Added in Ansible Tower 3.1.0_) Search across related fields:

	?related__search=findme
*/
func (a *Client) CredentialsCredentialsList(params *CredentialsCredentialsListParams, opts ...ClientOption) (*CredentialsCredentialsListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_list",
		Method:             "GET",
		PathPattern:        "/api/v2/credentials/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsObjectRolesList lists roles for a credential

Make a GET request to this resource to retrieve a list of
roles associated with the selected
credential.

The resulting data structure contains:

	{
	    "count": 99,
	    "next": null,
	    "previous": null,
	    "results": [
	        ...
	    ]
	}

The `count` field indicates the total number of roles
found for the given query.  The `next` and `previous` fields provides links to
additional results if there are more than will fit on a single page.  The
`results` list contains zero or more role records.

## Results

Each role data structure includes the following fields:

* `id`: Database ID for this role. (integer)
* `type`: Data type for this role. (choice)
* `url`: URL for this role. (string)
* `related`: Data structure with URLs of related resources. (object)
* `summary_fields`: Data structure with name/description for related resources.  The output for some objects may be limited for performance reasons. (object)
* `name`: Name of this role. (field)
* `description`: Optional description of this role. (field)

## Sorting

To specify that roles are returned in a particular
order, use the `order_by` query string parameter on the GET request.

	?order_by=name

Prefix the field name with a dash `-` to sort in reverse:

	?order_by=-name

Multiple sorting fields may be specified by separating the field names with a
comma `,`:

	?order_by=name,some_other_field

## Pagination

Use the `page_size` query string parameter to change the number of results
returned for each request.  Use the `page` query string parameter to retrieve
a particular page of results.

	?page_size=100&page=2

The `previous` and `next` links returned with the results will set these query
string parameters automatically.

## Searching

Use the `search` query string parameter to perform a case-insensitive search
within all designated text fields of a model.

	?search=findme

(_Added in Ansible Tower 3.1.0_) Search across related fields:

	?related__search=findme
*/
func (a *Client) CredentialsCredentialsObjectRolesList(params *CredentialsCredentialsObjectRolesListParams, opts ...ClientOption) (*CredentialsCredentialsObjectRolesListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsObjectRolesListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_object_roles_list",
		Method:             "GET",
		PathPattern:        "/api/v2/credentials/{id}/object_roles/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsObjectRolesListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsObjectRolesListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_object_roles_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsOwnerTeamsList lists teams for a credential

Make a GET request to this resource to retrieve a list of
teams associated with the selected
credential.

The resulting data structure contains:

	{
	    "count": 99,
	    "next": null,
	    "previous": null,
	    "results": [
	        ...
	    ]
	}

The `count` field indicates the total number of teams
found for the given query.  The `next` and `previous` fields provides links to
additional results if there are more than will fit on a single page.  The
`results` list contains zero or more team records.

## Results

Each team data structure includes the following fields:

* `id`: Database ID for this team. (integer)
* `type`: Data type for this team. (choice)
* `url`: URL for this team. (string)
* `related`: Data structure with URLs of related resources. (object)
* `summary_fields`: Data structure with name/description for related resources.  The output for some objects may be limited for performance reasons. (object)
* `created`: Timestamp when this team was created. (datetime)
* `modified`: Timestamp when this team was last modified. (datetime)
* `name`: Name of this team. (string)
* `description`: Optional description of this team. (string)
* `organization`:  (id)

## Sorting

To specify that teams are returned in a particular
order, use the `order_by` query string parameter on the GET request.

	?order_by=name

Prefix the field name with a dash `-` to sort in reverse:

	?order_by=-name

Multiple sorting fields may be specified by separating the field names with a
comma `,`:

	?order_by=name,some_other_field

## Pagination

Use the `page_size` query string parameter to change the number of results
returned for each request.  Use the `page` query string parameter to retrieve
a particular page of results.

	?page_size=100&page=2

The `previous` and `next` links returned with the results will set these query
string parameters automatically.

## Searching

Use the `search` query string parameter to perform a case-insensitive search
within all designated text fields of a model.

	?search=findme

(_Added in Ansible Tower 3.1.0_) Search across related fields:

	?related__search=findme
*/
func (a *Client) CredentialsCredentialsOwnerTeamsList(params *CredentialsCredentialsOwnerTeamsListParams, opts ...ClientOption) (*CredentialsCredentialsOwnerTeamsListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsOwnerTeamsListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_owner_teams_list",
		Method:             "GET",
		PathPattern:        "/api/v2/credentials/{id}/owner_teams/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsOwnerTeamsListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsOwnerTeamsListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_owner_teams_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsOwnerUsersList lists users for a credential

Make a GET request to this resource to retrieve a list of
users associated with the selected
credential.

The resulting data structure contains:

	{
	    "count": 99,
	    "next": null,
	    "previous": null,
	    "results": [
	        ...
	    ]
	}

The `count` field indicates the total number of users
found for the given query.  The `next` and `previous` fields provides links to
additional results if there are more than will fit on a single page.  The
`results` list contains zero or more user records.

## Results

Each user data structure includes the following fields:

* `id`: Database ID for this user. (integer)
* `type`: Data type for this user. (choice)
* `url`: URL for this user. (string)
* `related`: Data structure with URLs of related resources. (object)
* `summary_fields`: Data structure with name/description for related resources.  The output for some objects may be limited for performance reasons. (object)
* `created`: Timestamp when this user was created. (datetime)
* `modified`: Timestamp when this user was last modified. (datetime)
* `username`: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. (string)
* `first_name`:  (string)
* `last_name`:  (string)
* `email`:  (string)
* `is_superuser`: Designates that this user has all permissions without explicitly assigning them. (boolean)
* `is_system_auditor`:  (boolean)

* `ldap_dn`:  (string)
* `last_login`:  (datetime)
* `external_account`: Set if the account is managed by an external service (field)

## Sorting

To specify that users are returned in a particular
order, use the `order_by` query string parameter on the GET request.

	?order_by=username

Prefix the field name with a dash `-` to sort in reverse:

	?order_by=-username

Multiple sorting fields may be specified by separating the field names with a
comma `,`:

	?order_by=username,some_other_field

## Pagination

Use the `page_size` query string parameter to change the number of results
returned for each request.  Use the `page` query string parameter to retrieve
a particular page of results.

	?page_size=100&page=2

The `previous` and `next` links returned with the results will set these query
string parameters automatically.

## Searching

Use the `search` query string parameter to perform a case-insensitive search
within all designated text fields of a model.

	?search=findme

(_Added in Ansible Tower 3.1.0_) Search across related fields:

	?related__search=findme
*/
func (a *Client) CredentialsCredentialsOwnerUsersList(params *CredentialsCredentialsOwnerUsersListParams, opts ...ClientOption) (*CredentialsCredentialsOwnerUsersListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsOwnerUsersListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_owner_users_list",
		Method:             "GET",
		PathPattern:        "/api/v2/credentials/{id}/owner_users/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsOwnerUsersListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsOwnerUsersListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_owner_users_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsPartialUpdate updates a credential

Make a PUT or PATCH request to this resource to update this
credential.  The following fields may be modified:

* `name`: Name of this credential. (string, required)
* `description`: Optional description of this credential. (string, default=`""`)
* `organization`:  (id, default=`None`)
* `credential_type`: Specify the type of credential you want to create. Refer to the documentation for details on each type. (id, required)

* `inputs`: Enter inputs using either JSON or YAML syntax. Refer to the documentation for example syntax. (json, default=`{}`)

For a PATCH request, include only the fields that are being modified.
*/
func (a *Client) CredentialsCredentialsPartialUpdate(params *CredentialsCredentialsPartialUpdateParams, opts ...ClientOption) (*CredentialsCredentialsPartialUpdateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsPartialUpdateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_partial_update",
		Method:             "PATCH",
		PathPattern:        "/api/v2/credentials/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsPartialUpdateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsPartialUpdateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_partial_update: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsRead retrieves a credential

Make GET request to this resource to retrieve a single credential
record containing the following fields:

* `id`: Database ID for this credential. (integer)
* `type`: Data type for this credential. (choice)
* `url`: URL for this credential. (string)
* `related`: Data structure with URLs of related resources. (object)
* `summary_fields`: Data structure with name/description for related resources.  The output for some objects may be limited for performance reasons. (object)
* `created`: Timestamp when this credential was created. (datetime)
* `modified`: Timestamp when this credential was last modified. (datetime)
* `name`: Name of this credential. (string)
* `description`: Optional description of this credential. (string)
* `organization`:  (id)
* `credential_type`: Specify the type of credential you want to create. Refer to the documentation for details on each type. (id)
* `managed`:  (boolean)
* `inputs`: Enter inputs using either JSON or YAML syntax. Refer to the documentation for example syntax. (json)
* `kind`:  (field)
* `cloud`:  (field)
* `kubernetes`:  (field)
*/
func (a *Client) CredentialsCredentialsRead(params *CredentialsCredentialsReadParams, opts ...ClientOption) (*CredentialsCredentialsReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsReadParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_read",
		Method:             "GET",
		PathPattern:        "/api/v2/credentials/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsReadReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsReadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_read: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsTestCreate retrieves a credential

Make GET request to this resource to retrieve a single credential
record containing the following fields:
*/
func (a *Client) CredentialsCredentialsTestCreate(params *CredentialsCredentialsTestCreateParams, opts ...ClientOption) (*CredentialsCredentialsTestCreateCreated, *CredentialsCredentialsTestCreateAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsTestCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_test_create",
		Method:             "POST",
		PathPattern:        "/api/v2/credentials/{id}/test/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsTestCreateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *CredentialsCredentialsTestCreateCreated:
		return value, nil, nil
	case *CredentialsCredentialsTestCreateAccepted:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for credentials: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsTestRead retrieves a credential

Make GET request to this resource to retrieve a single credential
record containing the following fields:
*/
func (a *Client) CredentialsCredentialsTestRead(params *CredentialsCredentialsTestReadParams, opts ...ClientOption) (*CredentialsCredentialsTestReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsTestReadParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_test_read",
		Method:             "GET",
		PathPattern:        "/api/v2/credentials/{id}/test/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsTestReadReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsTestReadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_test_read: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	CredentialsCredentialsUpdate updates a credential

Make a PUT or PATCH request to this resource to update this
credential.  The following fields may be modified:

* `name`: Name of this credential. (string, required)
* `description`: Optional description of this credential. (string, default=`""`)
* `organization`:  (id, default=`None`)
* `credential_type`: Specify the type of credential you want to create. Refer to the documentation for details on each type. (id, required)

* `inputs`: Enter inputs using either JSON or YAML syntax. Refer to the documentation for example syntax. (json, default=`{}`)

For a PUT request, include **all** fields in the request.
*/
func (a *Client) CredentialsCredentialsUpdate(params *CredentialsCredentialsUpdateParams, opts ...ClientOption) (*CredentialsCredentialsUpdateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCredentialsCredentialsUpdateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Credentials_credentials_update",
		Method:             "PUT",
		PathPattern:        "/api/v2/credentials/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CredentialsCredentialsUpdateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CredentialsCredentialsUpdateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Credentials_credentials_update: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
