// Code generated by go-swagger; DO NOT EDIT.

package credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CredentialsCredentialsUpdateReader is a Reader for the CredentialsCredentialsUpdate structure.
type CredentialsCredentialsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CredentialsCredentialsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCredentialsCredentialsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCredentialsCredentialsUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCredentialsCredentialsUpdateOK creates a CredentialsCredentialsUpdateOK with default headers values
func NewCredentialsCredentialsUpdateOK() *CredentialsCredentialsUpdateOK {
	return &CredentialsCredentialsUpdateOK{}
}

/*
CredentialsCredentialsUpdateOK describes a response with status code 200, with default header values.

CredentialsCredentialsUpdateOK credentials credentials update o k
*/
type CredentialsCredentialsUpdateOK struct {
}

// IsSuccess returns true when this credentials credentials update o k response has a 2xx status code
func (o *CredentialsCredentialsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this credentials credentials update o k response has a 3xx status code
func (o *CredentialsCredentialsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this credentials credentials update o k response has a 4xx status code
func (o *CredentialsCredentialsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this credentials credentials update o k response has a 5xx status code
func (o *CredentialsCredentialsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this credentials credentials update o k response a status code equal to that given
func (o *CredentialsCredentialsUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *CredentialsCredentialsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /api/v2/credentials/{id}/][%d] credentialsCredentialsUpdateOK ", 200)
}

func (o *CredentialsCredentialsUpdateOK) String() string {
	return fmt.Sprintf("[PUT /api/v2/credentials/{id}/][%d] credentialsCredentialsUpdateOK ", 200)
}

func (o *CredentialsCredentialsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCredentialsCredentialsUpdateBadRequest creates a CredentialsCredentialsUpdateBadRequest with default headers values
func NewCredentialsCredentialsUpdateBadRequest() *CredentialsCredentialsUpdateBadRequest {
	return &CredentialsCredentialsUpdateBadRequest{}
}

/*
CredentialsCredentialsUpdateBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type CredentialsCredentialsUpdateBadRequest struct {
}

// IsSuccess returns true when this credentials credentials update bad request response has a 2xx status code
func (o *CredentialsCredentialsUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this credentials credentials update bad request response has a 3xx status code
func (o *CredentialsCredentialsUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this credentials credentials update bad request response has a 4xx status code
func (o *CredentialsCredentialsUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this credentials credentials update bad request response has a 5xx status code
func (o *CredentialsCredentialsUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this credentials credentials update bad request response a status code equal to that given
func (o *CredentialsCredentialsUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CredentialsCredentialsUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v2/credentials/{id}/][%d] credentialsCredentialsUpdateBadRequest ", 400)
}

func (o *CredentialsCredentialsUpdateBadRequest) String() string {
	return fmt.Sprintf("[PUT /api/v2/credentials/{id}/][%d] credentialsCredentialsUpdateBadRequest ", 400)
}

func (o *CredentialsCredentialsUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
