// Code generated by go-swagger; DO NOT EDIT.

package workflow_approval_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListReader is a Reader for the WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsList structure.
type WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK creates a WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK with default headers values
func NewWorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK() *WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK {
	return &WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK{}
}

/*
WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK describes a response with status code 200, with default header values.

WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK workflow approval templates workflow approval templates approvals list o k
*/
type WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK struct {
}

// IsSuccess returns true when this workflow approval templates workflow approval templates approvals list o k response has a 2xx status code
func (o *WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this workflow approval templates workflow approval templates approvals list o k response has a 3xx status code
func (o *WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this workflow approval templates workflow approval templates approvals list o k response has a 4xx status code
func (o *WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this workflow approval templates workflow approval templates approvals list o k response has a 5xx status code
func (o *WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this workflow approval templates workflow approval templates approvals list o k response a status code equal to that given
func (o *WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK) IsCode(code int) bool {
	return code == 200
}

func (o *WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/workflow_approval_templates/{id}/approvals/][%d] workflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK ", 200)
}

func (o *WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK) String() string {
	return fmt.Sprintf("[GET /api/v2/workflow_approval_templates/{id}/approvals/][%d] workflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK ", 200)
}

func (o *WorkflowApprovalTemplatesWorkflowApprovalTemplatesApprovalsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
